/* Mini-games (free, no wagering), Game Level, Lucky Bag, PK battle, missions/anniversary event, room music.
 * Game points come from playing — never from betting. Demo coins only appear in Lucky Bag (sharing) and PK support. */
(function () {
  const HD = window.HD, U = HD.utils, { esc, icon, $, $$ } = U, UI = HD.ui, R = HD.router, M = HD.modal, CS = HD.CONFIG.COIN_SYMBOL;
  const S = () => HD.state.getState(), cur = () => { const c = S().currentRoom; return c && HD.room(c.id); };

  // ---------- missions (daily) + anniversary milestone track ----------
  const MISSIONS = [['join', 'Join 3 rooms', 3, '🚪', { coins: 100 }], ['chat', 'Send 10 chat messages', 10, '💬', { bag: ['rose', 3] }], ['gift', 'Send a gift', 1, '🎁', { coins: 60 }], ['game', 'Play 3 mini-games', 3, '🎮', { bag: ['heart', 2] }], ['post', 'Post a moment', 1, '✨', { coins: 80 }], ['friend', 'Make a friend', 1, '🤝', { bag: ['coffee', 2] }], ['speak', 'Spend 30s on stage unmuted', 30, '🎙️', { coins: 120 }]];
  const MILES = [[3, 'Starter pack', { coins: 200 }], [6, 'Gift box', { bag: ['balloon', 5] }], [10, 'Big surprise', { bag: ['crown', 1] }]];
  const Ms = HD.missions = {
    st() { const s = S(); if (!s.missions || s.missions.day !== U.today()) s.missions = { day: U.today(), counts: {}, claimed: {}, miles: {} }; return s.missions; },
    inc(k, n = 1) { if (!S().currentUser) return; const m = Ms.st(); m.counts[k] = (m.counts[k] || 0) + n; HD.state.persistState(); },
    points() { const m = Ms.st(); return MISSIONS.filter(x => m.claimed[x[0]]).length; },
    reward(r) { const s = S(); if (r.coins) { s.wallet.balance += r.coins; HD.gifts.tx('bonus', r.coins, 'Mission reward'); } if (r.bag) HD.bag.add(r.bag[0], r.bag[1]); HD.progress.addXp(8, 'mission'); HD.state.persistState(); HD.bus.emit('wallet'); },
    claim(k) { const m = Ms.st(), x = MISSIONS.find(y => y[0] === k); if (!x || m.claimed[k] || (m.counts[k] || 0) < x[2]) return false; m.claimed[k] = true; Ms.reward(x[4]); return x; },
    claimMile(i) { const m = Ms.st(), x = MILES[i]; if (!x || m.miles[i] || Ms.points() < x[0]) return false; m.miles[i] = true; Ms.reward(x[2]); return x; }
  };
  const wrap = (obj, name, fn) => { const o = obj[name]; obj[name] = function (...a) { const r = o.apply(this, a); try { fn(r, a); } catch (e) { } return r; }; };
  wrap(HD.rooms, 'join', r => { if (r && r.ok && !r.already) Ms.inc('join'); });
  wrap(HD.gifts, 'send', r => { if (r && r.ok) Ms.inc('gift'); });
  wrap(HD.messages, 'sendRoom', r => { if (r && r.ok) Ms.inc('chat'); });
  wrap(HD.social, 'addFriend', () => setTimeout(() => Ms.inc('friend'), 2700)); wrap(HD.social, 'acceptRequest', () => Ms.inc('friend'));
  setInterval(() => { const r = cur(); if (r && r.seats.includes('me') && !r.muted.me) Ms.inc('speak'); }, 1000);

  R.add('missions', { title: 'Missions', nav: 'missions', render(v) {
    if (HD.me().isGuest) { v.innerHTML = UI.page(UI.top('Missions') + UI.empty('calendar', 'Account needed', 'Create a free local demo account to earn mission rewards.', '<button class="btn primary" data-go="#register">Create account</button>')); return; }
    const draw = () => { const m = Ms.st(), pts = Ms.points(), mx = MILES[2][0];
      v.innerHTML = UI.page(UI.top('Missions') + `<div class="vip-hero" style="--tc:#ff5fd2"><div class="vip-medal">🎉</div><h2>Anniversary event</h2><p class="muted small">Complete daily missions to fill the milestone bar. Resets every day. Demo rewards only.</p></div>
      <div class="card pad" style="margin-top:12px"><div class="row between"><b>Milestones</b><span class="muted small">${pts} / ${mx} points today</span></div><div class="bar" style="margin:10px 0"><i style="width:${Math.min(100, pts / mx * 100)}%"></i></div><div class="row" style="justify-content:space-between">${MILES.map((x, i) => `<button class="btn sm ${m.miles[i] ? '' : pts >= x[0] ? 'primary' : ''}" data-act="mileClaim" data-i="${i}" ${m.miles[i] || pts < x[0] ? 'disabled' : ''}>${m.miles[i] ? '✓' : '🎁'} ${x[0]} pts</button>`).join('')}</div></div>
      <div class="seg-title">DAILY MISSIONS</div><div class="group">${MISSIONS.map(x => { const c = Math.min(m.counts[x[0]] || 0, x[2]), done = c >= x[2], got = m.claimed[x[0]], rw = x[4].coins ? CS + ' ' + x[4].coins : (HD.state.getState().gifts.find(g => g.id === x[4].bag[0]) || {}).icon + ' ×' + x[4].bag[1];
        return `<div class="li"><span class="ic-wrap" style="font-size:20px">${x[3]}</span><span class="grow"><b>${x[1]}</b><div class="bar" style="margin-top:6px;height:6px"><i style="width:${c / x[2] * 100}%"></i></div><div class="muted small" style="margin-top:3px">${c}/${x[2]} · reward ${rw}</div></span><button class="btn sm ${done && !got ? 'primary' : ''}" data-act="msClaim" data-k="${x[0]}" ${!done || got ? 'disabled' : ''}>${got ? 'Claimed' : 'Claim'}</button></div>`; }).join('')}</div>`); };
    HD.act.msClaim = ({ k }) => { const x = Ms.claim(k); if (x) { HD.toast.ok('Reward claimed', 'gift'); HD.sfx.play('win'); draw(); } };
    HD.act.mileClaim = ({ i }) => { const x = Ms.claimMile(+i); if (x) { HD.fx.confetti(); HD.toast.ok('Milestone reward: ' + x[1], 'gift'); draw(); } };
    draw(); const t = setInterval(() => R.cur && R.cur.name === 'missions' && draw(), 4000); return () => clearInterval(t); } });

  // ---------- Game level ----------
  const GL = [[0, 'Bronze', '🥉', '#c0763a'], [200, 'Silver', '🥈', '#b9c2d0'], [800, 'Gold', '🥇', '#f5c451'], [2500, 'Platinum', '💠', '#7fd4ff'], [6000, 'Diamond', '💎', '#7c9dff'], [15000, 'Master', '🏆', '#ff5fd2']];
  HD.gameLevel = () => { const p = S().stats.gamePoints || 0; let i = 0; GL.forEach((g, k) => { if (p >= g[0]) i = k; }); return { i, g: GL[i], p, next: GL[i + 1] }; };
  HD.games = { award(win, label) { const s = S(); s.stats.gamesPlayed++; if (win) s.stats.gamesWon++; s.stats.gamePoints += win ? 12 : 4; Ms.inc('game'); HD.progress.addXp(3, 'game'); HD.state.persistState(); const r = cur(); if (r && label) HD.messages.system(r.id, `🎮 ${label}`); } };
  R.add('gamelevel', { title: 'Game level', nav: 'gamelevel', render(v) {
    const draw = () => { const L = HD.gameLevel(), g = L.g, pct = L.next ? Math.round((L.p - g[0]) / (L.next[0] - g[0]) * 100) : 100, s = S(), claimed = s.gameWeek === U.today().slice(0, 7) + '-' + Math.floor(new Date().getDate() / 7);
      v.innerHTML = UI.page(UI.top('Game level') + `<div class="vip-hero" style="--tc:${g[3]}"><div class="vip-medal">${g[2]}</div><h2>${g[1]}</h2><div class="muted small">${U.fmt(L.p)} game points · ${L.next ? U.fmt(L.next[0] - L.p) + ' to ' + L.next[1] : 'Top level'}</div><div class="bar" style="margin:12px auto 0;max-width:280px"><i style="width:${pct}%"></i></div></div>
      <div class="note" style="margin-top:12px">${icon('info', 18)}<div>Game points come from <b>playing</b> free mini-games (4 per game, 12 per win). No betting or wagering is involved.</div></div>
      <div class="seg-title">${g[1].toUpperCase()} PRIVILEGES</div><div class="shop-grid g3"><div class="shop-item"><div style="font-size:40px">${g[2]}</div><b style="font-size:12px">Game level logo</b></div><div class="shop-item"><div style="font-size:40px">🎁</div><b style="font-size:12px">Weekly reward</b><button class="btn sm primary" data-act="glClaim" ${claimed ? 'disabled' : ''}>${claimed ? 'Claimed' : 'Claim'}</button></div></div>
      <div class="seg-title">LEVELS</div><div class="group">${GL.map((x, i) => `<div class="li" style="${i > L.i ? 'opacity:.5' : ''}"><span class="ic-wrap" style="font-size:20px">${x[2]}</span><span class="grow"><b>${x[1]}</b><div class="muted small">${U.fmt(x[0])} points</div></span>${i <= L.i ? icon('check', 18) : icon('lock', 16)}</div>`).join('')}</div><button class="btn primary block" style="margin-top:14px" data-act="openGamesHub">Play games</button>`); };
    HD.act.glClaim = () => { const L = HD.gameLevel(), s = S(); s.gameWeek = U.today().slice(0, 7) + '-' + Math.floor(new Date().getDate() / 7); HD.bag.add(['rose', 'heart', 'star', 'moon', 'crown', 'diamond'][Math.min(5, L.i)], 3 + L.i); HD.toast.ok('Weekly reward added to your bag', 'gift'); HD.state.persistState(); draw(); };
    HD.act.openGamesHub = () => { const r = cur(); r ? HD.gamesPanel(r.id) : HD.toast.show('Join a room to play together', { icon: 'mic' }); }; draw(); } });

  // ---------- games panel ----------
  const GAMES = [['wheel', '🎡', 'Turntable'], ['dice', '🎲', 'Dice duel'], ['mora', '✊', 'Hand game'], ['guess', '🔢', 'Number guess'], ['coin', '🪙', 'Coin flip'], ['trivia', '🧠', 'Trivia'], ['bag', '🧧', 'Lucky bag'], ['pk', '⚔️', 'PK battle']];
  const DARES = ['Tell us your most-played song', 'Do your best animal impression', 'Share an embarrassing (harmless) story', 'Speak in rhyme for one minute', 'Name 5 countries in 10 seconds', 'Describe your day as a movie trailer', 'Sing the chorus of a song you know', 'Give someone a sincere compliment', 'Share one thing you are proud of', 'Say a tongue twister three times'];
  const TRIVIA = [['Which planet has the most moons (2024)?', ['Saturn', 'Jupiter', 'Mars'], 0], ['What does CPU stand for?', ['Central Processing Unit', 'Computer Power Unit', 'Core Program Utility'], 0], ['Which language runs in web browsers?', ['JavaScript', 'COBOL', 'Fortran'], 0], ['How many continents are there?', ['Seven', 'Five', 'Nine'], 0], ['What gas do plants absorb?', ['Carbon dioxide', 'Neon', 'Helium'], 0], ['Which is the largest ocean?', ['Pacific', 'Atlantic', 'Indian'], 0], ['HTTP status 404 means…', ['Not found', 'Server error', 'Forbidden'], 0], ['Who wrote “Romeo and Juliet”?', ['Shakespeare', 'Dickens', 'Tolstoy'], 0], ['What is 12 × 12?', ['144', '124', '164'], 0], ['Binary 101 equals…', ['5', '3', '7'], 0], ['Capital of Japan?', ['Tokyo', 'Osaka', 'Kyoto'], 0], ['Which is NOT a programming language?', ['Cobra Kai', 'Python', 'Rust'], 0]];
  const shuffle = a => a.map(x => [Math.random(), x]).sort((p, q) => p[0] - q[0]).map(x => x[1]);
  HD.gamesPanel = roomId => {
    const h = M.open({ title: '🎮 Games', body: `<div class="note" style="margin-bottom:12px">${icon('info', 18)}<div>Free mini-games for fun and Game level points. No betting.</div></div><div class="sounds">${GAMES.map(g => `<button data-game="${g[0]}"><span class="e">${g[1]}</span>${g[2]}</button>`).join('')}</div>`,
      onOpen: hh => hh.el.addEventListener('click', e => { const b = e.target.closest('[data-game]'); if (b) { hh.close(); setTimeout(() => HD.playGame(b.dataset.game, roomId), 230); } }) });
  };
  const sheet = (title, html, onOpen) => M.open({ title, body: html, actions: [{ label: 'Close', kind: 'ghost' }], onOpen });
  HD.playGame = (g, roomId) => {
    const r = roomId && HD.room(roomId), name = HD.me().name;
    if (g === 'wheel') { let rot = 0, busy = false;
      sheet('🎡 Turntable', `<div class="center"><div id="wh" class="wheel" aria-label="Wheel">${DARES.map((d, i) => `<span style="--i:${i}">${i + 1}</span>`).join('')}</div><div class="wpin">▼</div><p id="wr" class="muted" style="min-height:44px;margin:10px 0">Spin to get a challenge.</p><button class="btn primary" id="ws">Spin</button></div>`, h => $('#ws', h.el).addEventListener('click', () => { if (busy) return; busy = true; const idx = Math.floor(Math.random() * DARES.length); rot += 1440 + (360 - idx * 36 - 18) - (rot % 360); $('#wh', h.el).style.transform = `rotate(${rot}deg)`; setTimeout(() => { busy = false; $('#wr', h.el).textContent = `#${idx + 1}: ${DARES[idx]}`; HD.games.award(true, `${name} spun the turntable: ${DARES[idx]}`); }, HD.reducedMotion() ? 50 : 2300); }));
    } else if (g === 'dice') { const d = () => 1 + Math.floor(Math.random() * 6); sheet('🎲 Dice duel', `<div class="center"><div class="dice-row"><div><div id="d1" class="die">?</div><small>You</small></div><b>vs</b><div><div id="d2" class="die">?</div><small>Rival</small></div></div><p id="dr" class="muted" style="margin:12px 0;min-height:24px">Highest total wins.</p><button class="btn primary" id="dg">Roll</button></div>`, h => $('#dg', h.el).addEventListener('click', () => { const a = d() + d(), b = d() + d(); $('#d1', h.el).textContent = a; $('#d2', h.el).textContent = b; const win = a > b; $('#dr', h.el).textContent = a === b ? 'Draw — roll again!' : win ? 'You win! 🎉' : 'Rival wins this time'; if (a !== b) HD.games.award(win, `${name} ${win ? 'won' : 'lost'} a dice duel (${a} vs ${b})`); }));
    } else if (g === 'mora') { const O = [['✊', 'Rock'], ['✋', 'Paper'], ['✌️', 'Scissors']]; sheet('✊ Hand game', `<div class="center"><div class="row" style="justify-content:center;gap:12px">${O.map((o, i) => `<button class="die" data-m="${i}" aria-label="${o[1]}">${o[0]}</button>`).join('')}</div><p id="mr" class="muted" style="margin:14px 0;min-height:40px">Choose your hand.</p></div>`, h => h.el.addEventListener('click', e => { const b = e.target.closest('[data-m]'); if (!b) return; const me = +b.dataset.m, bot = Math.floor(Math.random() * 3), res = me === bot ? 0 : (me - bot + 3) % 3 === 1 ? 1 : -1; $('#mr', h.el).innerHTML = `${O[me][0]} vs ${O[bot][0]} — ${res === 0 ? 'Draw' : res > 0 ? 'You win! 🎉' : 'You lose'}`; if (res !== 0) HD.games.award(res > 0, `${name} ${res > 0 ? 'won' : 'lost'} a hand game`); }));
    } else if (g === 'guess') { const n = 1 + Math.floor(Math.random() * 100); let left = 6; sheet('🔢 Number guess', `<div class="center"><p class="muted">I picked 1–100. You have <b id="gl">6</b> tries.</p><div class="row" style="margin:12px 0"><input id="gi" class="input" type="number" min="1" max="100" inputmode="numeric" aria-label="Your guess"><button class="btn primary" id="gb">Guess</button></div><p id="gr" style="min-height:24px"></p></div>`, h => { const go = () => { if (left <= 0) return; const v = +$('#gi', h.el).value; if (!v || v < 1 || v > 100) return HD.toast.err('Enter 1–100'); left--; $('#gl', h.el).textContent = left; if (v === n) { $('#gr', h.el).textContent = `Correct! It was ${n} 🎉`; left = 0; HD.games.award(true, `${name} guessed the number`); } else if (left === 0) { $('#gr', h.el).textContent = `Out of tries — it was ${n}`; HD.games.award(false, `${name} missed the number`); } else $('#gr', h.el).textContent = v < n ? 'Higher ⬆️' : 'Lower ⬇️'; }; $('#gb', h.el).addEventListener('click', go); $('#gi', h.el).addEventListener('keydown', e => e.key === 'Enter' && go()); });
    } else if (g === 'coin') { sheet('🪙 Coin flip', `<div class="center"><div id="cf" class="die" style="font-size:44px">🪙</div><p class="muted" style="margin:12px 0">Call it:</p><div class="row" style="justify-content:center"><button class="btn" data-c="0">Heads</button><button class="btn" data-c="1">Tails</button></div><p id="cr" style="min-height:24px;margin-top:10px"></p></div>`, h => h.el.addEventListener('click', e => { const b = e.target.closest('[data-c]'); if (!b) return; const res = Math.random() < .5 ? 0 : 1, win = res === +b.dataset.c; $('#cf', h.el).textContent = res ? '🔵' : '🟡'; $('#cr', h.el).textContent = `${res ? 'Tails' : 'Heads'} — ${win ? 'you win! 🎉' : 'not this time'}`; HD.games.award(win, `${name} ${win ? 'won' : 'lost'} a coin flip`); }));
    } else if (g === 'trivia') { const qs = shuffle(TRIVIA).slice(0, 5); let i = 0, score = 0; const h = sheet('🧠 Trivia', '<div id="tv"></div>', hh => { const draw = () => { const el = $('#tv', hh.el); if (i >= qs.length) { el.innerHTML = `<div class="center"><div style="font-size:54px">${score >= 4 ? '🏆' : '👏'}</div><h2>${score}/5 correct</h2></div>`; HD.games.award(score >= 3, `${name} scored ${score}/5 in trivia`); return; } const q = qs[i], opts = shuffle(q[1].map((t, k) => [t, k === q[2]])); el.innerHTML = `<p class="muted small">Question ${i + 1}/5</p><h3 style="margin:6px 0 12px">${esc(q[0])}</h3><div class="col">${opts.map(o => `<button class="btn block" data-ok="${o[1] ? 1 : 0}">${esc(o[0])}</button>`).join('')}</div>`; }; hh.el.addEventListener('click', e => { const b = e.target.closest('[data-ok]'); if (!b) return; if (b.dataset.ok === '1') { score++; b.classList.add('primary'); } else b.classList.add('danger'); $$('[data-ok]', hh.el).forEach(x => x.disabled = true); setTimeout(() => { i++; draw(); }, 600); }); draw(); });
    } else if (g === 'bag') { if (!r) return HD.toast.show('Open a room first'); if (!r.seats.includes('me')) return HD.toast.show('Get on stage to drop a bag', { icon: 'hand' }); if (HD.me().isGuest) return M.requireAccount('drop lucky bags');
      M.open({ title: '🧧 Lucky bag', body: `<p class="muted small" style="margin-bottom:10px">Share demo coins with the room. The amount is split randomly among the slots; anyone can grab one within 25 seconds. Unclaimed coins return to you.</p><div class="field"><label for="lb-t">Total coins</label><select id="lb-t" class="input">${[100, 300, 500, 1000, 5000].map(x => `<option>${x}</option>`).join('')}</select></div><div class="field"><label for="lb-s">Slots</label><select id="lb-s" class="input">${[3, 5, 8, 10].map(x => `<option>${x}</option>`).join('')}</select></div>`, actions: [{ label: 'Cancel', kind: 'ghost' }, { label: 'Drop bag', kind: 'primary', onClick: h => { const x = HD.rooms.dropBag(r.id, +$('#lb-t', h.el).value, +$('#lb-s', h.el).value); if (!x.ok) { HD.toast.err(x.msg); return false; } HD.toast.ok('Lucky bag dropped!', 'gift'); } }] });
    } else if (g === 'pk') { if (!r) return HD.toast.show('Open a room first'); if (!HD.rooms.can(r, 'chat')) return HD.toast.show('Only hosts and moderators can start a PK', { icon: 'shield' }); const x = HD.rooms.startPK(r.id); x.ok ? HD.toast.ok('PK battle started!', 'bolt') : HD.toast.err(x.msg); }
  };

  // ---------- Lucky bag + PK (room state) ----------
  Object.assign(HD.rooms, {
    dropBag(id, total, slots) { const r = HD.room(id), s = S(); if (!r) return { ok: false, msg: 'No room' }; if (r.luckyBag && r.luckyBag.ends > Date.now()) return { ok: false, msg: 'A bag is already active' }; if (s.wallet.balance < total) return { ok: false, msg: 'Not enough demo coins' };
      s.wallet.balance -= total; HD.gifts.tx('shop', -total, 'Lucky bag dropped'); const w = Array.from({ length: slots }, () => .2 + Math.random()), sum = w.reduce((a, b) => a + b, 0), amts = w.map(x => Math.max(1, Math.floor(total * x / sum))); amts[0] += total - amts.reduce((a, b) => a + b, 0);
      r.luckyBag = { by: 'me', total, amts, claimed: [], ends: Date.now() + 25000 }; HD.messages.system(id, `🧧 You dropped a lucky bag (${total} coins, ${slots} slots)`); HD.sfx.play('gift'); HD.bus.emit('wallet'); this.emit(); return { ok: true }; },
    grabBag(id, uid) { const r = HD.room(id), b = r && r.luckyBag; if (!b || b.ends < Date.now() || b.claimed.length >= b.amts.length || b.claimed.some(c => c.uid === uid)) return { ok: false }; const amt = b.amts[b.claimed.length]; b.claimed.push({ uid, amt }); if (uid === 'me') { const s = S(); s.wallet.balance += amt; HD.gifts.tx('bonus', amt, 'Lucky bag grabbed'); HD.bus.emit('wallet'); HD.toast.ok('You grabbed ' + amt + ' coins!', 'gift'); HD.sfx.play('win'); } this.emit(); return { ok: true, amt }; },
    startPK(id) { const r = HD.room(id); if (!r) return { ok: false, msg: 'No room' }; if (r.pk && r.pk.ends > Date.now()) return { ok: false, msg: 'A PK is already running' }; const o = r.seats.filter(x => x !== r.hostId); if (!o.length) return { ok: false, msg: 'Need a second speaker on stage' }; r.pk = { a: r.hostId, b: o[0], sa: 0, sb: 0, ends: Date.now() + 45000, done: false }; HD.messages.system(id, `⚔️ PK battle: ${HD.user(r.hostId).name} vs ${HD.user(o[0]).name}`); this.emit(); return { ok: true }; },
    supportPK(id, side, amt) { const r = HD.room(id), s = S(); if (!r || !r.pk || r.pk.done) return { ok: false, msg: 'No PK running' }; if (s.wallet.balance < amt) return { ok: false, msg: 'Not enough demo coins' }; s.wallet.balance -= amt; HD.gifts.tx('gift', -amt, 'PK support'); r.pk[side === 'a' ? 'sa' : 'sb'] += amt; r.contrib = r.contrib || {}; r.contrib.me = (r.contrib.me || 0) + amt; r.giftsTotal += amt; HD.bus.emit('wallet'); this.emit(); return { ok: true }; }
  });
  HD.roomUI.bag = r => { const b = r.luckyBag; if (!b) return ''; const left = Math.max(0, Math.ceil((b.ends - Date.now()) / 1000)), open = left > 0 && b.claimed.length < b.amts.length, mine = b.claimed.find(c => c.uid === 'me');
    return `<section class="poll" aria-label="Lucky bag"><div class="row between"><b>🧧 Lucky bag from ${b.by === 'me' ? 'you' : esc(HD.user(b.by).name)}</b><span class="bdg ${open ? 'live' : ''}">${open ? left + 's' : 'Done'}</span></div><div class="row between" style="margin-top:8px"><span class="muted small">${b.claimed.length}/${b.amts.length} grabbed${mine ? ' · you got ' + mine.amt : ''}</span>${open && !mine && b.by !== 'me' ? '<button class="btn sm primary" data-act="bagGrab">Grab</button>' : ''}</div></section>`; };
  HD.roomUI.pk = r => { const p = r.pk; if (!p) return ''; const t = p.sa + p.sb || 1, left = Math.max(0, Math.ceil((p.ends - Date.now()) / 1000)), a = HD.user(p.a), b = HD.user(p.b), win = p.done ? (p.sa === p.sb ? 'Draw' : (p.sa > p.sb ? a.name : b.name) + ' wins!') : '';
    return `<section class="poll" aria-label="PK battle"><div class="row between"><b>⚔️ PK battle</b><span class="bdg ${p.done ? '' : 'live'}">${p.done ? win : left + 's'}</span></div><div class="row" style="margin-top:10px">${UI.av(a, { s: 40 })}<div class="grow"><div class="pkbar"><i style="width:${p.sa / t * 100}%"></i><u style="width:${p.sb / t * 100}%"></u></div><div class="row between small muted" style="margin-top:4px"><span>${esc(a.name)} · ${U.fmt(p.sa)}</span><span>${U.fmt(p.sb)} · ${esc(b.name)}</span></div></div>${UI.av(b, { s: 40 })}</div>${p.done ? '<div class="row" style="margin-top:8px;justify-content:flex-end"><button class="btn sm ghost" data-act="pkClear">Dismiss</button></div>' : `<div class="row" style="margin-top:8px"><button class="btn sm grow" data-act="pkSup" data-s="a" data-n="10">Support ${esc(a.name)} · ${CS}10</button><button class="btn sm grow" data-act="pkSup" data-s="b" data-n="10">Support ${esc(b.name)} · ${CS}10</button></div>`}</section>`; };
  Object.assign(HD.act, { bagGrab: () => { const r = cur(); r && HD.rooms.grabBag(r.id, 'me'); }, pkSup: ({ s, n }) => { const r = cur(), x = r && HD.rooms.supportPK(r.id, s, +n); x && !x.ok && HD.toast.err(x.msg); }, pkClear: () => { const r = cur(); if (r) { delete r.pk; HD.rooms.emit(); } } });
  setInterval(() => { const r = cur(); if (!r) return; let ch = false; const b = r.luckyBag; if (b) { const open = b.ends > Date.now() && b.claimed.length < b.amts.length; if (open) { const pool = r.seats.concat(r.audience).filter(x => x !== 'me' && x !== b.by && !b.claimed.some(c => c.uid === x)); if (pool.length && Math.random() < .6) { HD.rooms.grabBag(r.id, U.pick(pool)); } else ch = true; } else if (!b.done) { b.done = true; const left = b.amts.slice(b.claimed.length).reduce((a, c) => a + c, 0); if (b.by === 'me' && left) { S().wallet.balance += left; HD.gifts.tx('bonus', left, 'Lucky bag refund'); HD.bus.emit('wallet'); HD.toast.show('Unclaimed ' + left + ' coins returned', { icon: 'wallet' }); } ch = true; setTimeout(() => { if (r.luckyBag === b) { delete r.luckyBag; HD.rooms.emit(); } }, 6000); } }
    const p = r.pk; if (p && !p.done) { if (p.ends > Date.now()) { if (Math.random() < .8) { const k = Math.random() < .5 ? 'sa' : 'sb'; p[k] += [10, 20, 50, 100][Math.floor(Math.random() * 4)]; } ch = true; } else { p.done = true; const myWin = (p.a === 'me' && p.sa > p.sb) || (p.b === 'me' && p.sb > p.sa); if (p.a === 'me' || p.b === 'me') HD.games.award(myWin, 'PK battle finished'); HD.messages.system(r.id, '⚔️ PK finished: ' + (p.sa === p.sb ? 'draw' : (p.sa > p.sb ? HD.user(p.a).name : HD.user(p.b).name) + ' wins')); ch = true; } } if (ch) HD.rooms.emit(); }, 1000);

  // ---------- room music (generated) ----------
  let mctx = null, mnodes = [], mtimer = null;
  HD.music = { on: false, toggle() { this.on ? this.stop() : this.start(); HD.bus.emit('room:change'); return this.on; },
    start() { const C = window.AudioContext || window.webkitAudioContext; if (!C) return false; mctx = mctx || new C(); if (mctx.state === 'suspended') mctx.resume(); this.on = true; const master = mctx.createGain(); master.gain.value = (S().settings.audio.volume / 100) * .06; master.connect(mctx.destination); mnodes = [master];
      const chords = [[220, 277, 330, 415], [196, 247, 294, 370], [175, 220, 262, 330], [165, 208, 247, 311]]; let step = 0;
      const play = () => { const ch = chords[step++ % chords.length], t = mctx.currentTime; ch.forEach((f, i) => { const o = mctx.createOscillator(), g = mctx.createGain(); o.type = i % 2 ? 'sine' : 'triangle'; o.frequency.value = f; g.gain.setValueAtTime(0, t); g.gain.linearRampToValueAtTime(.5, t + 1.2); g.gain.linearRampToValueAtTime(0, t + 4.6); o.connect(g); g.connect(master); o.start(t); o.stop(t + 4.8); }); };
      play(); mtimer = setInterval(play, 4000); return true; },
    stop() { this.on = false; clearInterval(mtimer); mtimer = null; mnodes.forEach(n => { try { n.disconnect(); } catch (e) { } }); mnodes = []; } };
  HD.bus.on('room:ended', () => HD.music.on && HD.music.stop());
})();
