/* Moments (social feed), Messages v2 (tabs, official + system rows, friend search), Search v2 (Room / User tabs). */
(function () {
  const HD = window.HD, U = HD.utils, { esc, icon, $, $$ } = U, UI = HD.ui, R = HD.router, M = HD.modal, t = k => HD.t(k);
  const S = () => HD.state.getState();
  const nameHTML = u => `<span class="${HD.cosmetic.nameCls(u.id)}" style="${HD.cosmetic.nameStyle(u.id)}">${esc(u.name)}</span>`;
  const img = p => p.img ? (HD.storage.images['mm:' + p.id] || U.cover(p.img)) : null;

  // ---------- Moments ----------
  R.add('moments', { title: 'Moments', nav: 'moments', render(v) {
    let tab = 'trending', topic = null; const TABS = [['follow', 'Follow'], ['trending', 'Trending'], ['topic', 'Topic']];
    v.innerHTML = UI.page(`<header class="topbar"><h1>Moments</h1><button class="icon-btn" data-go="#search" aria-label="Search">${icon('search', 20)}</button></header><div class="tabs" role="tablist" id="mo-t"></div><div id="mo-b" style="margin-top:12px"></div><button class="fab" data-act="momentNew" aria-label="New moment">${icon('edit', 24)}</button>`);
    const card = p => { const u = HD.user(p.by), mine = p.by === 'me', liked = p.likes.includes('me'), long = p.text.length > 120;
      return `<article class="post mpost" data-pid="${p.id}"><div class="row"><span data-user="${u.id}" role="button" tabindex="0" aria-label="${esc(u.name)}">${UI.av(u, { s: 44 })}</span><div class="grow"><div class="trunc"><b>${nameHTML(u)}</b> ${UI.tierPill(u.tier, 1)} <span class="lvl" style="font-size:10px;padding:1px 7px">Lv ${u.level}</span></div><div class="faint small">${U.ago(p.ts)} · ${U.date(p.ts)}</div></div>${mine ? '' : UI.followBtn(u.id)}${mine ? `<button class="icon-btn" style="width:34px;height:34px" data-act="momentDel" data-id="${p.id}" aria-label="Delete moment">${icon('trash', 15)}</button>` : ''}</div>
        <button class="chip" style="margin:10px 0 6px;height:30px" data-act="momentTopic" data-t="${esc(p.topic)}">#${esc(p.topic)}</button><p style="margin:2px 0 8px">${esc(long ? p.text.slice(0, 120) + '…' : p.text)} ${long ? `<button class="link" style="color:var(--accent-t);font-weight:650" data-act="momentMore" data-id="${p.id}">More</button>` : ''}</p>
        ${img(p) ? `<div class="mimg" style="background-image:url('${img(p)}')" role="img" aria-label="Moment photo"></div>` : ''}
        <div class="row between" style="margin-top:8px"><button class="mact ${liked ? 'on' : ''}" data-act="momentLike" data-id="${p.id}" aria-pressed="${liked}" aria-label="Like, ${p.likes.length}">${icon('heart', 18)} ${p.likes.length}</button><button class="mact" data-act="momentComment" data-id="${p.id}" aria-label="Comments, ${p.comments.length}">${icon('chat', 18)} ${p.comments.length}</button><button class="mact" data-act="momentGift" data-id="${p.id}" aria-label="Send a rose">${icon('gift', 18)} ${p.gifts || ''}</button><button class="mact" data-act="momentShare" data-id="${p.id}" aria-label="Copy text">${icon('share', 18)}</button></div></article>`; };
    const list = () => { const s = S(); let a = s.moments.filter(p => !s.social.blocked.includes(p.by)); if (tab === 'follow') a = a.filter(p => p.by === 'me' || s.social.following.includes(p.by)); if (topic) a = a.filter(p => p.topic === topic); return a.slice().sort((x, y) => tab === 'trending' ? (y.likes.length * 3 + y.comments.length * 2 + y.ts / 36e5 / 1e3) - (x.likes.length * 3 + x.comments.length * 2 + x.ts / 36e5 / 1e3) : y.ts - x.ts); };
    const draw = () => { $('#mo-t', v).innerHTML = TABS.map(x => `<button class="tab ${x[0] === tab ? 'on' : ''}" role="tab" aria-selected="${x[0] === tab}" data-mt="${x[0]}">${x[1]}</button>`).join('');
      const weekly = `<div class="banner" data-act="momentTopic" data-t="MyFirstRoom" role="button" tabindex="0"><b>WEEKLY TOPIC</b><span>#MyFirstRoom · post to earn bonus XP</span></div>`;
      const topics = tab === 'topic' ? `<div class="hscroll noscroll-x" style="margin-bottom:10px">${HD.demo.TOPICS.map(x => `<button class="chip ${topic === x ? 'on' : ''}" data-act="momentTopic" data-t="${x}">#${x}</button>`).join('')}</div>` : topic ? `<div class="row" style="margin-bottom:8px"><span class="chip on">#${esc(topic)}</span><button class="btn sm ghost" data-act="momentTopic" data-t="">Clear</button></div>` : '';
      const l = list(); $('#mo-b', v).innerHTML = (tab === 'trending' && !topic ? weekly : '') + topics + (l.length ? l.map(card).join('') : UI.empty('compass', tab === 'follow' ? 'Nothing from people you follow' : 'No moments here', tab === 'follow' ? 'Follow people to fill this feed.' : 'Be the first to post.', '<button class="btn primary" data-act="momentNew">New moment</button>')); };
    v.addEventListener('click', e => { const b = e.target.closest('[data-mt]'); if (b) { tab = b.dataset.mt; if (tab !== 'topic') topic = null; draw(); } });
    HD.act.momentTopic = ({ t: tp }) => { topic = tp && tp !== topic ? tp : null; if (topic) tab = 'topic'; draw(); };
    HD.act.momentMore = ({ id }) => { const p = S().moments.find(x => x.id === id); M.open({ title: HD.user(p.by).name, body: `<p>${esc(p.text)}</p>`, actions: [{ label: 'Close', kind: 'primary' }] }); };
    HD.act.momentLike = ({ id }) => { if (!M.requireAccount('like moments')) return; const p = S().moments.find(x => x.id === id), i = p.likes.indexOf('me'); i < 0 ? p.likes.push('me') : p.likes.splice(i, 1); HD.state.persistState(); draw(); };
    HD.act.momentGift = ({ id }) => { if (!M.requireAccount('send gifts')) return; const p = S().moments.find(x => x.id === id), s = S(); if (p.by === 'me') return HD.toast.show('You cannot gift yourself'); if (s.wallet.balance < 10) { HD.toast.err('Not enough demo coins'); return M.recharge(); } const r = HD.gifts.send({ giftId: 'rose', toId: p.by, roomId: null, qty: 1 }); if (r.ok) { p.gifts = (p.gifts || 0) + 1; HD.fx.play(s.gifts.find(g => g.id === 'rose'), 'You', HD.user(p.by).name); HD.toast.ok('Rose sent 🌹', 'gift'); draw(); } };
    HD.act.momentShare = async ({ id }) => { const p = S().moments.find(x => x.id === id); HD.toast.ok(await U.copy(`“${p.text}” — ${HD.user(p.by).name} on ${HD.CONFIG.APP_NAME}`) ? 'Copied to clipboard' : 'Copy failed', 'share'); };
    HD.act.momentDel = async ({ id }) => { if (await M.confirm('Delete this moment?', 'This cannot be undone.', { ok: 'Delete', danger: true })) { const s = S(); s.moments = s.moments.filter(p => p.id !== id); HD.storage.delImage('mm:' + id); HD.state.persistState(); draw(); } };
    HD.act.momentComment = ({ id }) => { const p = S().moments.find(x => x.id === id); const render = () => `<div class="col" style="gap:10px;max-height:46vh;overflow:auto" id="cm-l">${p.comments.length ? p.comments.map(c => `<div class="row" style="align-items:flex-start">${UI.av(HD.user(c.by), { s: 34 })}<div class="grow"><b>${c.by === 'me' ? 'You' : esc(HD.user(c.by).name)}</b> <span class="faint tiny">${U.ago(c.ts)}</span><div>${esc(c.text)}</div></div></div>`).join('') : '<p class="muted center">No comments yet.</p>'}</div><form class="row" id="cm-f" style="margin-top:12px"><input class="input grow" id="cm-i" maxlength="160" placeholder="Add a comment…" aria-label="Comment" autocomplete="off"><button class="btn primary sm" type="submit">Send</button></form>`;
      M.open({ title: 'Comments', body: render(), onOpen: h => { const bind = () => $('#cm-f', h.el).addEventListener('submit', e => { e.preventDefault(); if (!M.requireAccount('comment')) return; const i = $('#cm-i', h.el), tx = i.value.trim(); if (!tx) return; p.comments.push({ by: 'me', text: tx, ts: Date.now() }); HD.state.persistState(); h.body.innerHTML = render(); bind(); draw(); setTimeout(() => { if (!document.contains(h.el)) return; p.comments.push({ by: U.pick(S().users).id, text: U.pick(['Love this!', 'Same here 😄', 'Well said 💜', 'Haha true', 'Sending good vibes']), ts: Date.now() }); HD.state.persistState(); h.body.innerHTML = render(); bind(); draw(); }, 1800); }); bind(); } }); };
    HD.act.momentNew = () => { if (!M.requireAccount('post moments')) return; let photo = null;
      M.open({ title: 'New moment', body: `<div class="field"><label for="mn-t">What's on your mind?</label><textarea id="mn-t" class="input" maxlength="300" placeholder="Share something…"></textarea></div><div class="field"><label for="mn-p">Topic</label><select id="mn-p" class="input">${HD.demo.TOPICS.map(x => `<option>${x}</option>`).join('')}</select></div><div class="field"><label for="mn-f">Photo (optional)</label><input id="mn-f" type="file" accept="image/*" class="input" style="padding:10px"><div id="mn-pv"></div></div>`,
        actions: [{ label: 'Cancel', kind: 'ghost' }, { label: 'Post', kind: 'primary', onClick: h => { const tx = $('#mn-t', h.el).value.trim(); if (!tx) { HD.toast.err('Write something first'); return false; } const s = S(), id = U.uid('mm'), tp = $('#mn-p', h.el).value; if (photo) HD.storage.putImage('mm:' + id, photo); s.moments.unshift({ id, by: 'me', text: tx, topic: tp, ts: Date.now(), likes: [], comments: [], img: photo ? 'mine' : null, gifts: 0 }); s.stats.posts++; HD.missions.inc('post'); HD.progress.addXp(tp === 'MyFirstRoom' ? 25 : 10, 'post'); HD.state.persistState(); HD.toast.ok('Moment posted', 'compass'); tab = 'follow'; draw(); } }],
        onOpen: h => $('#mn-f', h.el).addEventListener('change', async e => { const f = e.target.files[0]; if (!f) return; try { photo = await U.resizeImage(f, 720); $('#mn-pv', h.el).innerHTML = `<img src="${photo}" alt="Preview" style="height:90px;border-radius:12px;margin-top:6px">`; } catch (x) { HD.toast.err('Could not read that image'); } }) }); };
    draw(); return HD.bus.on('moments', draw);
  } });
  // bots like / comment on my moments
  setInterval(() => { const s = S(); if (!s.currentUser || document.hidden) return; const mine = s.moments.filter(p => p.by === 'me' && p.likes.length < 40); if (!mine.length || Math.random() > .5) return; const p = U.pick(mine), pool = s.users.filter(u => !p.likes.includes(u.id) && !s.social.blocked.includes(u.id)); if (!pool.length) return; const u = U.pick(pool); p.likes.push(u.id); s.stats.momentLikes++; HD.notify.add({ type: 'moment', from: u.id, text: 'liked your moment ❤️' }); HD.state.persistState(); HD.bus.emit('moments'); }, 12000);

  // ---------- Messages v2 ----------
  const oldMsg = R.routes.messages.render;
  R.routes.messages.render = function (v, params) {
    if (params[0]) return oldMsg(v, params); let tab = 'msg', q = '';
    const row = (ic, bg, title, sub, ts, go, badge) => `<button class="li" data-go="${go}"><span class="av-ic" style="background:${bg}">${ic}</span><span class="grow"><b>${title}</b><div class="muted small trunc">${esc(sub)}</div></span><span class="col" style="align-items:flex-end;gap:4px"><span class="faint tiny">${ts}</span>${badge ? `<span class="ub">${badge}</span>` : ''}</span></button>`;
    const draw = () => { const cs = HD.messages.conversations(), s = S(), sys = HD.notify.list().filter(n => n.type === 'system' || n.type === 'reward' || n.type === 'achievement')[0], mom = HD.notify.list().filter(n => n.type === 'moment' || n.type === 'follow')[0], off = s.official[0], offUn = s.official.filter(o => !o.read).length;
      v.innerHTML = UI.page(`<header class="topbar"><h1 class="sr-only">${t('messages')}</h1><div class="tabs grow" style="max-width:240px" role="tablist">${[['msg', t('messages')], ['friend', 'Friends']].map(x => `<button class="tab ${x[0] === tab ? 'on' : ''}" role="tab" aria-selected="${x[0] === tab}" data-mt="${x[0]}">${x[1]}</button>`).join('')}</div><span class="grow"></span><button class="btn sm" data-act="msgClear">${icon('trash', 14)} Clear</button><button class="icon-btn" data-go="#friends" aria-label="Friend requests">${icon('users', 19)}${s.social.requests.length ? `<span class="dot">${s.social.requests.length}</span>` : ''}</button></header>
      ${tab === 'msg' ? `<div class="note" style="margin-bottom:10px">${icon('info', 18)}<div>Local demo messages. Contacts are simulated and replies are scripted.</div></div><div class="group">${row('📢', 'linear-gradient(135deg,#4da3ff,#7c6bff)', 'System notification', sys ? sys.text : 'Nothing new', sys ? U.ago(sys.ts) : '', '#notifications', HD.notify.unread() || '')}${row('📣', 'linear-gradient(135deg,#a56bff,#ff5fd2)', 'Official announcement', off ? off.title : '', off ? U.ago(off.ts) : '', '#announcements', offUn || '')}${row('✨', 'linear-gradient(135deg,#3ddc97,#39b8ff)', 'Moment notification', mom ? (mom.from ? HD.user(mom.from).name + ' ' : '') + mom.text : 'No activity yet', mom ? U.ago(mom.ts) : '', '#notifications', '')}${cs.map(c => { const u = HD.user(c.userId), ms = HD.messages.thread(c.userId), l = ms[ms.length - 1]; return `<button class="li" data-go="#messages/${c.userId}">${UI.av(u, { s: 50, online: true })}<span class="grow"><b>${esc(u.name)}</b> ${UI.tierPill(u.tier, 1)}<div class="muted small trunc">${l ? (l.from === 'me' ? 'You: ' : '') + (l.audio ? '🎤 Voice note' : esc(l.text)) : 'Say hi'}</div></span><span class="col" style="align-items:flex-end;gap:4px"><span class="faint tiny">${U.ago(c.last)}</span>${c.unread ? `<span class="ub">${c.unread}</span>` : ''}</span></button>`; }).join('')}</div>`
        : `<input id="fq" class="input" type="search" placeholder="Search username / ID" aria-label="Search username or ID" value="${esc(q)}" style="border-radius:999px;margin-bottom:12px"><div id="fl"></div>`}`);
      if (tab === 'friend') { const fl = $('#fl', v), f = x => !q || (x.name + ' ' + x.handle + ' ' + HD.displayId(x)).toLowerCase().includes(q.toLowerCase()), friends = s.friends.map(HD.user).filter(f), sug = s.users.filter(u => !s.friends.includes(u.id) && !s.social.blocked.includes(u.id) && f(u)).slice(0, 10);
        fl.innerHTML = `<div class="seg-title">FRIENDS (${friends.length})</div>${friends.length ? `<div class="group">${friends.map(u => UI.userRow(u, `<button class="btn sm primary" data-act="dmUser" data-id="${u.id}" aria-label="Message ${esc(u.name)}">${icon('send', 15)}</button>`)).join('')}</div>` : '<p class="muted small">No friends match.</p>'}<div class="seg-title">NEW FRIENDS</div><div class="group">${sug.map(u => UI.userRow(u, `<span class="row" style="gap:6px"><button class="btn sm" data-act="addF" data-id="${u.id}" ${HD.social.isPending(u.id) ? 'disabled' : ''}>${HD.social.isPending(u.id) ? 'Requested' : 'Add'}</button><button class="btn sm primary" data-act="dmUser" data-id="${u.id}" aria-label="Say hi">${icon('send', 15)}</button></span>`)).join('')}</div>`;
        const fq = $('#fq', v); fq.addEventListener('input', U.debounce(e => { q = e.target.value; draw(); const n = $('#fq', v); n.focus(); n.setSelectionRange(q.length, q.length); }, 250)); } };
    v.addEventListener('click', e => { const b = e.target.closest('[data-mt]'); if (b) { tab = b.dataset.mt; draw(); } });
    HD.act.msgClear = async () => { if (await M.confirm('Clear unread?', 'Marks every message and notification as read.', { ok: 'Clear' })) { S().conversations.forEach(c => c.unread = 0); HD.notify.markAll(); S().official.forEach(o => o.read = true); HD.state.persistState(); HD.bus.emit('dm'); draw(); } };
    draw(); const o1 = HD.bus.on('dm', () => { if (R.cur && R.cur.name === 'messages' && !R.cur.params[0]) draw(); }), o2 = HD.bus.on('notif', () => { if (R.cur && R.cur.name === 'messages' && !R.cur.params[0] && tab === 'msg') draw(); }); return () => { o1(); o2(); };
  };
  R.add('announcements', { title: 'Announcements', nav: 'messages', public: false, render(v) {
    const s = S(); v.innerHTML = UI.page(UI.top('Official announcements') + `<div class="col">${s.official.map(o => `<div class="card pad ${o.read ? '' : 'unread-card'}"><div class="row between"><b>${esc(o.title)}</b><span class="faint tiny">${U.ago(o.ts)}</span></div><p class="muted" style="margin-top:6px">${esc(o.text)}</p></div>`).join('')}</div>`); s.official.forEach(o => o.read = true); HD.state.persistState(); HD.bus.emit('dm'); } });
  UI.officialUnread = () => S().official.filter(o => !o.read).length;

  // ---------- Search v2: Room / User tabs + "You may like" ----------
  R.routes.search.render = function (v) {
    const st = S(); let tab = 'room';
    v.innerHTML = UI.page(`<header class="topbar"><button class="icon-btn" data-back aria-label="Back">${icon('back')}</button><h1 class="sr-only">Search</h1><input id="s-q" class="input" style="min-height:42px;border-radius:999px" type="search" placeholder="Search for rooms or users" aria-label="Search" autocomplete="off"></header><div class="tabs" role="tablist" id="s-t"></div><div id="s-out" style="margin-top:6px"></div>`);
    const q = $('#s-q', v), out = $('#s-out', v); q.focus();
    const run = () => { $('#s-t', v).innerHTML = [['room', 'Room'], ['user', 'User']].map(x => `<button class="tab ${x[0] === tab ? 'on' : ''}" role="tab" aria-selected="${x[0] === tab}" data-stab="${x[0]}">${x[1]}</button>`).join('');
      const s = q.value.trim().toLowerCase();
      if (!s) { const rs = st.recentSearches; const rec = rs.length ? `<div class="sect-h" style="margin-top:14px"><h3>Recent</h3><button class="link" data-act="clearRecent">Clear history</button></div><div class="row wrap">${rs.map(x => `<button class="chip" data-act="useSearch" data-q="${esc(x)}">${icon('history', 14)} ${esc(x)}</button>`).join('')}</div>` : '';
        out.innerHTML = rec + `<div class="seg-title">YOU MAY LIKE</div>` + (tab === 'room' ? `<div class="col">${HD.rooms.list({ sort: 'trending' }).slice(0, 5).map(UI.roomRow).join('')}</div>` : `<div class="group">${st.users.filter(u => !st.social.blocked.includes(u.id) && !HD.social.isFollowing(u.id)).sort((a, b) => HD.demo.compat(HD.me(), b) - HD.demo.compat(HD.me(), a)).slice(0, 8).map(u => UI.userRow(u, UI.followBtn(u.id))).join('')}</div>`); return; }
      if (tab === 'room') { const rooms = HD.rooms.list({ q: s }).slice(0, 12), cats = HD.demo.CATEGORIES.filter(c => c[1].toLowerCase().includes(s)); out.innerHTML = (cats.length ? `<div class="row wrap" style="margin:8px 0">${cats.map(c => `<button class="chip" data-act="goCat" data-c="${c[0]}">${c[1]}</button>`).join('')}</div>` : '') + (rooms.length ? `<div class="col" style="margin-top:8px">${rooms.map(UI.roomRow).join('')}</div>` : UI.empty('search', 'No rooms found', 'Try a name, ID, topic or host.')); }
      else { const users = st.users.filter(u => !st.social.blocked.includes(u.id) && (u.name + ' ' + u.handle + ' ' + u.country + ' ' + HD.displayId(u) + ' ' + u.id).toLowerCase().includes(s)).slice(0, 12); out.innerHTML = users.length ? `<div class="group" style="margin-top:8px">${users.map(u => UI.userRow(u, u.id === 'me' ? '' : UI.followBtn(u.id))).join('')}</div>` : UI.empty('user', 'No users found', 'Search by name, username or ID.'); } };
    const save = U.debounce(() => { const s = q.value.trim(); if (s.length > 1) { st.recentSearches = [s].concat(st.recentSearches.filter(x => x.toLowerCase() !== s.toLowerCase())).slice(0, 8); HD.state.persistState(); } }, 900);
    q.addEventListener('input', () => { run(); save(); }); v.addEventListener('click', e => { const b = e.target.closest('[data-stab]'); if (b) { tab = b.dataset.stab; run(); } });
    run(); UI.searchRun = run; UI.searchSet = s => { q.value = s; run(); q.focus(); };
  };

  // ---------- Visitors (simulated profile views) ----------
  R.add('visitors', { title: 'Visitors', nav: 'profile', render(v) {
    const s = S(), list = s.visitors.filter(x => !s.social.blocked.includes(x.uid));
    v.innerHTML = UI.page(UI.top('Visitors') + `<p class="muted small" style="margin-bottom:10px">People who looked at your profile (simulated).</p>` + (list.length ? `<div class="group">${list.slice(0, 80).map(x => UI.userRow(HD.user(x.uid), `<span class="faint small">${U.ago(x.ts)}</span>`)).join('')}</div>` : UI.empty('eye', 'No visitors yet', 'Host a room or post a moment to get noticed.')));
  } });
  setInterval(() => { const s = S(); if (!s.currentUser || s.currentUser.isGuest || document.hidden || Math.random() > .5) return; const pool = s.users.filter(u => !s.social.blocked.includes(u.id)); if (!pool.length) return; const u = U.pick(pool); s.visitors.unshift({ uid: u.id, ts: Date.now() }); if (s.visitors.length > 100) s.visitors.length = 100; s.stats.visitors = (s.stats.visitors || 0) + 1; HD.state.persistState(); }, 25000);
})();
