/* Props store: headwear (avatar frames), mounts (entrance rides), chat bubbles, relationship cards & rings,
 * room themes, plus a backpack. Rentals (7 / 30 days / forever) and gifting. Demo coins only. */
(function () {
  const HD = window.HD, U = HD.utils, { esc, icon, $ } = U, UI = HD.ui, R = HD.router, M = HD.modal, CS = HD.CONFIG.COIN_SYMBOL;
  const S = () => HD.state.getState(), DUR = [[7, 1, '7 days'], [30, 3, '30 days'], [0, 9, 'Forever']];
  const GRAD = { sunset: 'linear-gradient(160deg,#ff7a59,#c2185b 55%,#2a0a3a)', ocean: 'linear-gradient(160deg,#0a6cff,#0a2a66 55%,#04101f)', forest: 'linear-gradient(160deg,#1f9d63,#0b3b2a 55%,#04140e)', neon: 'radial-gradient(60% 60% at 20% 20%,#ff2bd6,transparent 60%),radial-gradient(60% 60% at 90% 40%,#00e5ff,transparent 60%),#0a0614', mono: 'linear-gradient(160deg,#3a3a3a,#0b0b0b)' };
  // catalogue: [kind, id, name, emoji, price, rental?, requirement fn or null, requirement text]
  const C = [];
  HD.demo.FRAMES.forEach(f => C.push({ kind: 'frame', id: f.id, name: f.name, price: f.price }));
  C.push({ kind: 'frame', id: 'royal', name: 'Royal Laurel', price: 0, req: () => HD.vip.current() >= 2, reqText: 'VIP Flare+' }, { kind: 'frame', id: 'prestige', name: 'Prestige Halo', price: 0, req: () => HD.prestige.level() >= 2, reqText: 'Prestige 2' });
  [['racer', 'Neon Racer', '🏎️', 1500], ['unicorn', 'Star Unicorn', '🦄', 3000], ['ufo', 'Visitor UFO', '🛸', 2500], ['rocket', 'Rocket Sled', '🚀', 4000], ['dragon', 'Ember Dragon', '🐉', 6000]].forEach(m => C.push({ kind: 'mount', id: m[0], name: m[1], emoji: m[2], price: m[3], rental: true }));
  C.push({ kind: 'mount', id: 'steed', name: 'Crown Steed', emoji: '🐎', price: 0, req: () => HD.vip.current() >= 3, reqText: 'VIP Blaze+' });
  [['aqua', 'Aqua Glass', 1400], ['rose', 'Rose Quartz', 1400], ['royal', 'Royal Gold', 2400], ['neon', 'Neon Frame', 1800]].forEach(b => C.push({ kind: 'bubble', id: b[0], name: b[1], price: b[2], rental: true }));
  [['cp', 'CP card', '💞', 1888], ['soulmate', 'Soulmate card', '🤝', 1000], ['bestie', 'Bestie card', '💗', 1000], ['homie', 'Homie card', '✊', 1000]].forEach(c => C.push({ kind: 'card', id: c[0], name: c[1], emoji: c[2], price: c[3] }));
  [['angel', 'Angel Cat Ring', '😺', 6000], ['ocean', 'Ocean Ring', '🌊', 8000]].forEach(c => C.push({ kind: 'ring', id: c[0], name: c[1], emoji: c[2], price: c[3], rental: true }));
  C.push({ kind: 'ring', id: 'swan', name: 'Swan Love', emoji: '🦢', price: 0, req: () => (S().cp && S().cp.level >= 3), reqText: 'CP level 3' }, { kind: 'ring', id: 'forever', name: 'Forever Love', emoji: '💍', price: 0, req: () => (S().cp && S().cp.level >= 5), reqText: 'CP level 5' });
  HD.demo.ROOM_THEMES.forEach(t => C.push({ kind: 'theme', id: t.id, name: t.name, price: t.price }));
  HD.PROPS = C; const find = (k, id) => C.find(x => x.kind === k && x.id === id);

  const Sh = HD.shop = {
    key: (k, id) => k + ':' + id,
    owns(k, id) { const s = S().shop, key = k + ':' + id, it = find(k, id); if (it && it.req && it.req()) return true; return s.owned.includes(key) && (!s.until[key] || s.until[key] > Date.now()); },
    owned: key => { const [k, id] = key.split(':'); return Sh.owns(k, id); },
    ownedThemes: () => HD.demo.ROOM_THEMES.filter(t => Sh.owns('theme', t.id)),
    price(it, days) { if (!it.rental) return it.price; const d = DUR.find(x => x[0] === days) || DUR[0]; return it.price * d[1]; },
    buy(kind, id, days) {
      const s = S(), it = find(kind, id); if (!it) return { ok: false, msg: 'Unknown item' }; if (it.req && !it.req()) return { ok: false, msg: 'Requires ' + it.reqText }; if (!it.price) return { ok: false, msg: 'This item is unlocked, not sold' };
      const key = kind + ':' + id, price = Sh.price(it, days); if (s.wallet.balance < price) return { ok: false, msg: 'Not enough demo coins' };
      s.wallet.balance -= price; HD.gifts.tx('shop', -price, 'Props · ' + it.name + (it.rental ? ' · ' + (days ? days + ' days' : 'forever') : ''));
      if (kind === 'card') { s.cards[id] = (s.cards[id] || 0) + 1; HD.progress.addXp(10, 'shop'); HD.state.persistState(); HD.bus.emit('wallet'); return { ok: true, item: it }; }
      if (!s.shop.owned.includes(key)) s.shop.owned.push(key); if (it.rental && days) s.shop.until[key] = Math.max(s.shop.until[key] || Date.now(), Date.now()) + days * 864e5; else delete s.shop.until[key];
      HD.progress.addXp(15, 'shop'); HD.state.persistState(); HD.bus.emit('wallet'); return { ok: true, item: it };
    },
    equip(kind, id) { const s = S(); if (!id) s.shop.equip[kind] = null; else if (Sh.owns(kind, id)) s.shop.equip[kind] = id; else return false; if (kind === 'frame') HD.me().frame = s.shop.equip.frame || null; HD.state.persistState(); HD.bus.emit('room:change'); return true; },
    equipped: kind => (S().shop.equip || {})[kind] || null,
    tick() { const s = S(); if (!s.currentUser) return; Object.keys(s.shop.equip).forEach(k => { const id = s.shop.equip[k]; if (id && !Sh.owns(k, id)) { s.shop.equip[k] = null; if (k === 'frame') HD.me().frame = null; } }); }
  };
  setInterval(Sh.tick, 20000);

  // ---------- entrance effect ----------
  HD.fx.entrance = (name, emoji, color) => { if (HD.reducedMotion()) return; const d = document.createElement('div'); d.className = 'entrance'; d.style.setProperty('--tc', color || '#a56bff'); d.innerHTML = `<span class="ride">${emoji || '✨'}</span><span class="who">${esc(name)} entered the room</span>`; document.body.appendChild(d); setTimeout(() => d.remove(), 3600); };
  HD.mountFor = uid => { if (uid === 'me') { const e = Sh.equipped('mount'); const it = e && find('mount', e); if (it && Sh.owns('mount', e)) return it.emoji; return HD.vip.has('entrance') ? HD.TIERS[HD.vip.current() - 1].emoji : null; } const u = HD.user(uid); return u.tier >= 3 ? HD.TIERS[u.tier - 1].emoji : null; };

  const gate = v => { if (HD.me().isGuest) { v.innerHTML = UI.page(UI.top('Props store') + UI.empty('star', 'Account needed', 'Create a free local demo account to shop.', '<button class="btn primary" data-go="#register">Create account</button>')); return true; } };
  const TABS = [['frame', 'Headwear'], ['mount', 'Mount'], ['bubble', 'Chat bubble'], ['rel', 'Relationships'], ['theme', 'Room theme'], ['bag', 'Backpack']];
  R.add('shop', { title: 'Props store', nav: 'shop', render(v) {
    if (gate(v)) return; let tab = 'frame', sub = 'card', sel = null, days = 7;
    const preview = (it) => { const me = HD.me(); if (!it) return `<span class="avw" style="--s:84px"><img class="av" src="${HD.userAvatar(me)}" alt=""></span>`; if (it.kind === 'frame') return `<span class="avw frame-${it.id}" style="--s:84px"><img class="av" src="${HD.userAvatar(me)}" alt=""></span>`; if (it.kind === 'mount' || it.kind === 'card' || it.kind === 'ring') return `<div style="font-size:70px;filter:drop-shadow(0 0 16px rgba(165,107,255,.6))" class="pop">${it.emoji}</div>`; if (it.kind === 'bubble') return `<div class="bub-${it.id}" style="font-size:15px;padding:8px 16px">Hello from the lounge 👋</div>`; if (it.kind === 'theme') return `<div class="rt-swatch" style="background:${GRAD[it.id]};width:150px"></div>`; return ''; };
    const card = it => { const own = it.kind === 'card' ? (S().cards[it.id] || 0) > 0 : Sh.owns(it.kind, it.id), on = sel && sel.kind === it.kind && sel.id === it.id, eq = Sh.equipped(it.kind) === it.id, locked = it.req && !it.req(), until = S().shop.until[it.kind + ':' + it.id];
      const vis = it.kind === 'frame' ? `<span class="avw frame-${it.id}" style="--s:56px;margin:6px"><img class="av" src="${HD.userAvatar(HD.me())}" alt=""></span>` : it.kind === 'theme' ? `<div class="rt-swatch" style="background:${GRAD[it.id]}"></div>` : it.kind === 'bubble' ? `<div class="bub-${it.id}" style="font-size:12px">Hi 👋</div>` : `<div style="font-size:40px">${it.emoji}</div>`;
      return `<button class="shop-item ${on ? 'eq' : ''}" data-sel="${it.kind}:${it.id}" aria-pressed="${on}" aria-label="${esc(it.name)}">${vis}<b style="font-size:13px">${esc(it.name)}</b>${it.kind === 'card' && own ? `<span class="bdg host">×${S().cards[it.id]}</span>` : eq ? '<span class="bdg host">Equipped</span>' : own ? `<span class="bdg">${until ? 'Until ' + U.date(until) : 'Owned'}</span>` : locked ? `<span class="small faint">${esc(it.reqText)}</span>` : it.price ? `<span class="small" style="color:var(--gold-t);font-weight:700">${CS} ${U.fmt(it.rental ? it.price : it.price)}${it.rental ? '/7d' : ''}</span>` : ''}</button>`; };
    const bar = () => { if (!sel) return '<p class="faint small center" style="margin-top:12px">Tap an item to preview it.</p>'; const own = Sh.owns(sel.kind, sel.id), eq = Sh.equipped(sel.kind) === sel.id, locked = sel.req && !sel.req();
      return `<div class="card pad col" style="margin-top:14px;gap:10px"><div class="row between"><b>${esc(sel.name)}</b>${sel.price ? `<span class="coin" style="height:28px">${CS} ${U.fmt(Sh.price(sel, sel.rental ? days : 0))}</span>` : `<span class="bdg">${locked ? 'Needs ' + esc(sel.reqText) : 'Unlocked'}</span>`}</div>
      ${sel.rental && sel.price ? `<div class="row" role="group" aria-label="Duration">${DUR.map(d => `<button class="chip ${d[0] === days ? 'on' : ''}" data-d="${d[0]}" aria-pressed="${d[0] === days}">${d[2]}</button>`).join('')}</div>` : ''}
      <div class="row">${sel.price ? `<button class="btn primary grow" data-act="propBuy">${own ? 'Extend' : 'Buy'}</button><button class="btn grow" data-act="propSend">Send as gift</button>` : ''}${own && sel.kind !== 'card' && sel.price !== undefined ? `<button class="btn ${eq ? '' : 'primary'} grow" data-act="propEquip">${eq ? 'Unequip' : 'Equip'}</button>` : ''}</div></div>`; };
    const draw = () => { const s = S(), eqf = Sh.equipped('frame');
      let items = ''; if (tab === 'rel') items = `<div class="row" style="margin:10px 0">${[['card', 'Cards'], ['ring', 'CP rings']].map(x => `<button class="chip ${x[0] === sub ? 'on' : ''}" data-sub="${x[0]}">${x[1]}</button>`).join('')}</div><div class="shop-grid g3">${C.filter(i => i.kind === sub).map(card).join('')}</div>`;
      else if (tab === 'bag') { const own = C.filter(i => Sh.owns(i.kind, i.id) && i.kind !== 'card'), bag = Object.keys(s.bag).filter(k => s.bag[k] > 0); items = `<div class="seg-title">PROPS</div>${own.length ? `<div class="shop-grid g3">${own.map(card).join('')}</div>` : UI.empty('star', 'Nothing here yet', 'Buy props to fill your backpack.')}<div class="seg-title">GIFT BAG</div>${bag.length ? `<div class="gifts">${bag.map(k => { const g = s.gifts.find(x => x.id === k); return `<div class="gift"><span class="e">${g.icon}</span><b>${esc(g.name)}</b><span>×${s.bag[k]}</span></div>`; }).join('')}</div>` : '<p class="muted small">Missions and events add gifts to your bag. Use them from the Bag tab in the gift panel.</p>'}`; }
      else items = `<div class="shop-grid g3">${C.filter(i => i.kind === tab).map(card).join('')}</div>`;
      v.innerHTML = UI.page(UI.top('Props store', { actions: `<span class="coin">${CS} ${U.fmt(s.wallet.balance)}</span>` }) + `<div class="card center" style="padding:16px;display:grid;place-items:center;min-height:130px;background:linear-gradient(160deg,rgba(var(--accent-rgb),.28),transparent)">${preview(sel)}</div><div class="tabs" style="margin-top:12px" role="tablist">${TABS.map(x => `<button class="tab ${x[0] === tab ? 'on' : ''}" role="tab" aria-selected="${x[0] === tab}" data-st="${x[0]}">${x[1]}</button>`).join('')}</div>${items}${tab === 'bag' ? '' : bar()}<div class="row" style="margin-top:14px"><button class="btn grow" data-act="recharge">${icon('plus', 16)} Add demo coins</button></div>`); };
    v.addEventListener('click', e => { const t = e.target.closest('[data-st]'), s2 = e.target.closest('[data-sub]'), it = e.target.closest('[data-sel]'), d = e.target.closest('[data-d]'); if (t) { tab = t.dataset.st; sel = null; draw(); } else if (s2) { sub = s2.dataset.sub; sel = null; draw(); } else if (it) { const [k, id] = it.dataset.sel.split(':'); sel = find(k, id); draw(); } else if (d) { days = +d.dataset.d; draw(); } });
    HD.act.propBuy = () => { const r = Sh.buy(sel.kind, sel.id, sel.rental ? days : 0); if (!r.ok) { HD.toast.err(r.msg); return /coins/.test(r.msg) && M.recharge(); } HD.fx.confetti(); HD.toast.ok(sel.name + ' unlocked', 'star'); if (sel.kind === 'frame' || sel.kind === 'mount' || sel.kind === 'bubble') Sh.equip(sel.kind, sel.id); draw(); };
    HD.act.propEquip = () => { Sh.equipped(sel.kind) === sel.id ? Sh.equip(sel.kind, null) : Sh.equip(sel.kind, sel.id); draw(); };
    HD.act.propSend = () => { const it = sel, st = S(), list = st.users.filter(u => !st.social.blocked.includes(u.id)).slice(0, 12);
      M.open({ title: 'Send ' + it.name, body: `<p class="muted small" style="margin-bottom:8px">Costs the 7-day price (${CS} ${U.fmt(it.price)}). Demo only.</p><div class="group">${list.map(u => `<button class="li" data-u="${u.id}">${UI.av(u, { s: 38 })}<span class="grow"><b>${esc(u.name)}</b></span></button>`).join('')}</div>`, onOpen: h => h.el.addEventListener('click', e => { const b = e.target.closest('[data-u]'); if (!b) return; if (st.wallet.balance < it.price) { HD.toast.err('Not enough demo coins'); return; } st.wallet.balance -= it.price; HD.gifts.tx('shop', -it.price, `Sent ${it.name} to ${HD.user(b.dataset.u).name}`); HD.progress.addXp(10, 'gift'); HD.state.persistState(); HD.bus.emit('wallet'); h.close(); HD.toast.ok(HD.user(b.dataset.u).name + ' loved it!', 'gift'); draw(); }) }); };
    draw(); return HD.bus.on('wallet', () => { }); } });
})();
