/* CP space (couple/partner bond with levels and intimacy), relationship cards, and Families (clubs with chat). All simulated. */
(function () {
  const HD = window.HD, U = HD.utils, { esc, icon, $, $$ } = U, UI = HD.ui, R = HD.router, M = HD.modal, CS = HD.CONFIG.COIN_SYMBOL;
  const S = () => HD.state.getState();
  const gate = (v, title) => { if (HD.me().isGuest) { v.innerHTML = UI.page(UI.top(title) + UI.empty('heart', 'Account needed', 'Create a free local demo account to use this.', '<button class="btn primary" data-go="#register">Create account</button>')); return true; } };

  // ---------- CP ----------
  const LV = [0, 100, 300, 700, 1500, 3000, 6000], CARD_TYPES = { cp: ['💞', 'CP card'], soulmate: ['🤝', 'Soulmate card'], bestie: ['💗', 'Bestie card'], homie: ['✊', 'Homie card'] };
  const CP = HD.cp = {
    level(i) { let l = 1; LV.forEach((t, k) => { if (i >= t) l = k + 1; }); return l; },
    gain(n) { const c = S().cp; if (!c) return; const before = c.level; c.intimacy += n; c.level = CP.level(c.intimacy); HD.state.persistState(); if (c.level > before) { HD.fx.confetti(); HD.toast.ok(`CP level ${c.level}!`, 'heart'); HD.notify.add({ type: 'system', text: `Your CP bond reached level ${c.level} 💞` }); } },
    invite(uid, type) { const s = S(); if (!(s.cards[type] > 0)) return { ok: false, msg: 'You need a ' + CARD_TYPES[type][1] + ' — buy one in the Props store' }; if (type === 'cp' && s.cp) return { ok: false, msg: 'You already have a CP' }; if (type !== 'cp' && s.relations.length >= 5) return { ok: false, msg: 'Relationship list is full (5)' }; if (type === 'cp' && s.relations.some(r => r.uid === uid)) { }
      s.cards[type]--; HD.state.persistState(); HD.toast.show(`${CARD_TYPES[type][1]} sent to ${HD.user(uid).name}…`, { icon: 'send' });
      setTimeout(() => { const t = S(); if (!t.currentUser) return; const likely = HD.social.isFollowing(uid) || t.match.matches.includes(uid) || U.hash(HD.me().handle + uid + type) % 100 < 65;
        if (likely) { if (type === 'cp') t.cp = { partnerId: uid, level: 1, intimacy: 0, since: Date.now() }; else t.relations.push({ type, uid, since: Date.now() }); HD.notify.add({ type: 'friend', from: uid, text: `accepted your ${CARD_TYPES[type][1]} ${CARD_TYPES[type][0]}` }); HD.fx.confetti(); HD.sfx.play('win'); HD.toast.ok(`${HD.user(uid).name} accepted!`, 'heart'); HD.progress.addXp(30, 'cp'); }
        else { t.cards[type] = (t.cards[type] || 0) + 1; HD.toast.show(`${HD.user(uid).name} declined — your card was returned`, { icon: 'info' }); } HD.state.persistState(); HD.bus.emit('bonds'); }, 2200); return { ok: true }; },
    dissolve() { const s = S(); s.cp = null; HD.state.persistState(); HD.bus.emit('bonds'); }
  };
  const og = HD.gifts.send; HD.gifts.send = function (a) { const r = og.call(this, a); try { const c = S().cp; if (r.ok && c && a.toId === c.partnerId) CP.gain(Math.max(1, Math.round(r.total / 10))); } catch (e) { } return r; };
  const om = HD.messages.sendDM; HD.messages.sendDM = function (uid, text) { const r = om.call(this, uid, text); try { const c = S().cp; if (r && r.ok && c && uid === c.partnerId) CP.gain(1); } catch (e) { } return r; };

  R.add('cp', { title: 'CP space', nav: 'cp', render(v) {
    if (gate(v, 'CP space')) return; const draw = () => { const s = S(), c = s.cp, me = HD.me();
      const cards = Object.keys(CARD_TYPES).map(k => `<div class="shop-item"><div style="font-size:34px">${CARD_TYPES[k][0]}</div><b style="font-size:12px">${CARD_TYPES[k][1]}</b><span class="bdg">×${s.cards[k] || 0}</span><button class="btn sm primary" data-act="bondInvite" data-k="${k}" ${(s.cards[k] || 0) ? '' : 'disabled'}>Send</button></div>`).join('');
      let top; if (c) { const p = HD.user(c.partnerId), nx = LV[c.level], pct = nx ? Math.round((c.intimacy - LV[c.level - 1]) / (nx - LV[c.level - 1]) * 100) : 100, days = Math.max(1, Math.ceil((Date.now() - c.since) / 864e5));
        top = `<div class="vip-hero" style="--tc:#ff6bd6"><div class="row" style="justify-content:center;gap:0">${UI.av(me, { s: 76 })}<span style="font-size:34px;margin:0 -8px;z-index:2" class="pop">💞</span>${UI.av(p, { s: 76 })}</div><h2 style="margin-top:10px">${esc(me.name)} & ${esc(p.name)}</h2><div class="muted small">Together ${days} day${days > 1 ? 's' : ''} · CP level ${c.level}</div><div class="bar" style="margin:12px auto 0;max-width:280px"><i style="width:${pct}%"></i></div><div class="muted small" style="margin-top:6px">Intimacy ${U.fmt(c.intimacy)}${nx ? ' / ' + U.fmt(nx) : ' · max'}</div></div>
        <div class="row" style="margin:12px 0"><button class="btn primary grow" data-act="cpGift">${icon('gift', 16)} Send gift</button><button class="btn grow" data-act="dmUser" data-id="${p.id}">${icon('chat', 16)} Message</button></div><p class="muted small">Gifts to your CP (+1 intimacy per 10 coins) and messages (+1) grow the bond. Level 3 unlocks the Swan Love ring, level 5 the Forever Love ring in the Props store.</p><button class="btn danger block" style="margin-top:8px" data-act="cpEnd">Dissolve CP</button>`; }
      else top = `<div class="vip-hero" style="--tc:#ff6bd6"><div class="vip-medal">💞</div><h2>No CP yet</h2><p class="muted small">Invite to be CP (0/1). You need a CP card from the Props store.</p><button class="btn primary" style="margin-top:8px" data-act="cpPick" data-k="cp">Invite someone</button></div>`;
      const rel = s.relations.length ? `<div class="seg-title">OTHER BONDS</div><div class="group">${s.relations.map(r => UI.userRow(HD.user(r.uid), `<span class="bdg host">${CARD_TYPES[r.type][0]} ${CARD_TYPES[r.type][1].replace(' card', '')}</span>`)).join('')}</div>` : '';
      v.innerHTML = UI.page(UI.top('CP space') + top + rel + `<div class="seg-title">RELATIONSHIP CARDS</div><div class="shop-grid g3">${cards}</div><button class="btn block" style="margin-top:12px" data-go="#shop">Get cards in the Props store</button>`); };
    HD.act.cpGift = () => { const c = S().cp; c && M.gift(null, c.partnerId); };
    HD.act.cpEnd = async () => { if (await M.confirm('Dissolve your CP bond?', 'Your CP level and intimacy will be reset.', { ok: 'Dissolve', danger: true })) CP.dissolve(); };
    HD.act.cpPick = HD.act.bondInvite = ({ k }) => { const s = S(), list = s.users.filter(u => !s.social.blocked.includes(u.id) && !(s.cp && s.cp.partnerId === u.id)).sort((a, b) => HD.demo.compat(HD.me(), b) - HD.demo.compat(HD.me(), a)).slice(0, 12);
      if (!(s.cards[k] > 0)) { HD.toast.err('You need a ' + CARD_TYPES[k][1] + ' first'); return R.go('#shop'); }
      M.open({ title: 'Send ' + CARD_TYPES[k][1], body: `<div class="group">${list.map(u => `<button class="li" data-u="${u.id}">${UI.av(u, { s: 40 })}<span class="grow"><b>${esc(u.name)}</b><div class="muted small">${HD.demo.compat(HD.me(), u)}% compatible</div></span></button>`).join('')}</div>`, onOpen: h => h.el.addEventListener('click', e => { const b = e.target.closest('[data-u]'); if (!b) return; const r = CP.invite(b.dataset.u, k); h.close(); if (!r.ok) HD.toast.err(r.msg); else draw(); }) }); };
    draw(); return HD.bus.on('bonds', () => R.cur && R.cur.name === 'cp' && draw()); } });

  // ---------- Families ----------
  const Fam = HD.family = {
    mine() { const s = S(); return s.families.find(f => f.id === s.myFamily) || null; },
    role: (f, uid) => f.owner === uid ? 'Owner' : f.admins.includes(uid) ? 'Admin' : 'Member',
    create(name, tag, desc) { const s = S(); if (s.myFamily) return { ok: false, msg: 'Leave your family first' }; if (s.wallet.balance < 1000) return { ok: false, msg: 'Creating a family costs 1,000 demo coins' }; if (s.families.some(f => f.name.toLowerCase() === name.toLowerCase())) return { ok: false, msg: 'That name is taken' };
      s.wallet.balance -= 1000; HD.gifts.tx('shop', -1000, 'Created family ' + name); const f = { id: U.uid('fam'), name, tag: tag.toUpperCase(), desc, owner: 'me', admins: [], members: ['me'], level: 1, xp: 0, notice: 'Welcome to our family!', chat: [] }; s.families.unshift(f); s.myFamily = f.id; HD.progress.addXp(30, 'family'); HD.state.persistState(); HD.bus.emit('wallet'); return { ok: true, f }; },
    join(id) { const s = S(), f = s.families.find(x => x.id === id); if (!f) return { ok: false, msg: 'Not found' }; if (s.myFamily) return { ok: false, msg: 'Leave your family first' }; if (f.members.length >= 50) return { ok: false, msg: 'Family is full' }; f.members.push('me'); s.myFamily = id; f.chat.push({ by: f.owner, text: 'Welcome ' + HD.me().name + '! 🎉', ts: Date.now() }); HD.progress.addXp(15, 'family'); HD.state.persistState(); return { ok: true }; },
    leave() { const s = S(), f = Fam.mine(); if (!f) return; f.members = f.members.filter(x => x !== 'me'); f.admins = f.admins.filter(x => x !== 'me'); if (f.owner === 'me') { f.owner = f.admins[0] || f.members[0] || null; if (!f.owner) s.families = s.families.filter(x => x !== f); } s.myFamily = null; HD.state.persistState(); },
    lvl: f => 1 + Math.floor(Math.sqrt(f.xp / 100))
  };
  HD.familyTag = u => { if (!u || u.id !== 'me') return ''; const f = Fam.mine(); return f ? `<span class="bdg" style="background:rgba(var(--accent-rgb),.25);color:var(--text)">[${esc(f.tag)}]</span>` : ''; };
  setInterval(() => { const s = S(); if (!s.currentUser) return; s.families.forEach(f => { f.xp += Math.floor(Math.random() * 6); f.level = Fam.lvl(f); if (f.id === s.myFamily && Math.random() < .3 && R.cur && R.cur.name === 'family' && R.cur.params[0] === f.id) { const o = f.members.filter(x => x !== 'me'); if (o.length) { f.chat.push({ by: U.pick(o), text: U.pick(HD.demo.chatter()), ts: Date.now() }); HD.bus.emit('familychat', f.id); } } }); }, 6000);

  R.add('family', { title: 'Family', nav: 'family', render(v, [id]) {
    if (gate(v, 'Family')) return; return id ? detail(v, id) : list(v); } });
  function list(v) {
    const draw = () => { const s = S(), mine = Fam.mine(), others = s.families.filter(f => f !== mine).sort((a, b) => b.xp - a.xp);
      const row = f => `<button class="li" data-go="#family/${f.id}"><span class="av-ic" style="background:linear-gradient(135deg,hsl(${U.hash(f.id) % 360} 70% 50%),hsl(${(U.hash(f.id) + 60) % 360} 70% 35%));font:800 14px var(--mono);color:#fff">${esc(f.tag)}</span><span class="grow"><b>${esc(f.name)}</b> <span class="lvl" style="font-size:10px;padding:1px 7px">Lv ${Fam.lvl(f)}</span><div class="muted small trunc">${f.members.length} members · ${esc(f.desc)}</div></span>${icon('chev', 18, 'chev')}</button>`;
      v.innerHTML = UI.page(UI.top('Family', { actions: `<button class="btn sm primary" data-act="famNew">${icon('plus', 15)} Create</button>` }) + (mine ? `<div class="seg-title">MY FAMILY</div><div class="group">${row(mine)}</div>` : `<div class="note" style="margin-bottom:12px">${icon('info', 18)}<div>Join a family to chat with its members and grow it together. Creating one costs 1,000 demo coins.</div></div>`) + `<div class="seg-title">ALL FAMILIES</div><div class="group">${others.map(row).join('')}</div>`); };
    HD.act.famNew = () => { M.open({ title: 'Create a family', body: `<div class="field"><label for="fn">Name</label><input id="fn" class="input" maxlength="24"></div><div class="field"><label for="ft">Tag (3 letters)</label><input id="ft" class="input" maxlength="3" style="text-transform:uppercase"></div><div class="field"><label for="fd">Description</label><input id="fd" class="input" maxlength="60"></div><p class="faint small">Costs ${CS} 1,000 demo coins.</p>`, actions: [{ label: 'Cancel', kind: 'ghost' }, { label: 'Create', kind: 'primary', onClick: h => { const n = $('#fn', h.el).value.trim(), t = $('#ft', h.el).value.trim(); if (n.length < 3 || !/^[A-Za-z0-9]{3}$/.test(t)) { HD.toast.err('Name 3+ chars and a 3-letter tag'); return false; } const r = Fam.create(n, t, $('#fd', h.el).value.trim() || 'A new family'); if (!r.ok) { HD.toast.err(r.msg); return false; } HD.fx.confetti(); HD.toast.ok('Family created', 'users'); setTimeout(() => R.go('#family/' + r.f.id), 200); } }] }); };
    draw(); return HD.bus.on('wallet', () => { }); }
  function detail(v, id) {
    const f0 = S().families.find(f => f.id === id); if (!f0) { v.innerHTML = UI.page(UI.top('Family') + UI.empty('users', 'Family not found', '')); return; }
    const draw = () => { const s = S(), f = f0, mine = s.myFamily === f.id, owner = f.owner === 'me', pct = Math.round((f.xp - 100 * (Fam.lvl(f) - 1) ** 2) / (100 * (Fam.lvl(f) ** 2 - (Fam.lvl(f) - 1) ** 2)) * 100);
      v.innerHTML = UI.page(UI.top(f.name) + `<div class="vip-hero" style="--tc:hsl(${U.hash(f.id) % 360} 75% 60%)"><div class="sid-big" style="font-size:34px">[${esc(f.tag)}]</div><h2>${esc(f.name)}</h2><div class="muted small">${esc(f.desc)} · Level ${Fam.lvl(f)} · ${f.members.length} members</div><div class="bar" style="margin:10px auto 0;max-width:260px"><i style="width:${Math.max(4, pct)}%"></i></div></div>
        <div class="note" style="margin-top:12px">${icon('mega', 18)}<div><b>Notice</b><br>${esc(f.notice)}${owner ? ' <button class="link" style="color:var(--accent-t)" data-act="famNotice">Edit</button>' : ''}</div></div>
        <div class="row" style="margin:12px 0">${mine ? `<button class="btn grow" data-act="famCheckin" ${s.famCheck === U.today() ? 'disabled' : ''}>${s.famCheck === U.today() ? 'Checked in' : 'Daily check-in'}</button><button class="btn danger grow" data-act="famLeave">Leave</button>` : `<button class="btn primary block" data-act="famJoin" data-id="${f.id}">Join family</button>`}</div>
        ${mine ? `<div class="seg-title">FAMILY CHAT</div><div class="card pad" id="fchat" style="max-height:260px;overflow:auto">${f.chat.length ? f.chat.slice(-40).map(m => `<div class="cmsg"><span>${UI.av(HD.user(m.by), { s: 30 })}</span><div class="txt"><b>${m.by === 'me' ? 'You' : esc(HD.user(m.by).name)}</b> <span class="faint tiny">${U.time(m.ts)}</span><div>${esc(m.text)}</div></div></div>`).join('') : '<p class="muted center">Say hello!</p>'}</div><form class="composer" id="ff"><input class="input grow" id="fi" maxlength="200" placeholder="Message the family…" aria-label="Family message" autocomplete="off"><button class="icon-btn" type="submit" aria-label="Send" style="background:linear-gradient(120deg,var(--accent),var(--accent2));color:var(--accent-ink)">${icon('send', 18)}</button></form>` : ''}
        <div class="seg-title">MEMBERS</div><div class="group">${f.members.map(m => UI.userRow(HD.user(m), `<span class="bdg ${f.owner === m ? 'host' : f.admins.includes(m) ? 'mod' : ''}">${Fam.role(f, m)}</span>`)).join('')}</div>`);
      const ff = $('#ff', v); if (ff) ff.addEventListener('submit', e => { e.preventDefault(); const i = $('#fi', v), tx = i.value.trim(); if (!tx) return; f.chat.push({ by: 'me', text: tx, ts: Date.now() }); f.xp += 2; HD.state.persistState(); draw(); const b = $('#fchat', v); b && (b.scrollTop = b.scrollHeight); $('#fi', v).focus(); }); const b = $('#fchat', v); b && (b.scrollTop = b.scrollHeight); };
    HD.act.famJoin = ({ id: i }) => { const r = Fam.join(i); r.ok ? (HD.toast.ok('Welcome to the family!', 'users'), draw()) : HD.toast.err(r.msg); };
    HD.act.famLeave = async () => { if (await M.confirm('Leave this family?', 'You can join another one later.', { ok: 'Leave', danger: true })) { Fam.leave(); R.go('#family'); } };
    HD.act.famCheckin = () => { const s = S(); s.famCheck = U.today(); f0.xp += 20; s.wallet.balance += 50; HD.gifts.tx('bonus', 50, 'Family check-in'); HD.progress.addXp(8, 'family'); HD.state.persistState(); HD.bus.emit('wallet'); HD.toast.ok('+50 coins · +20 family XP', 'users'); draw(); };
    HD.act.famNotice = async () => { const t = await M.prompt('Family notice', { label: 'Message for members', value: f0.notice, max: 120 }); if (t) { f0.notice = t; HD.state.persistState(); draw(); } };
    draw(); return HD.bus.on('familychat', i => { if (i === id && R.cur && R.cur.name === 'family') draw(); }); }
})();
