/* Screens: wallet, rewards, host center, history, settings, help, about, demo info */
(function () {
  const HD = window.HD, U = HD.utils, { esc, icon, $, $$ } = U, UI = HD.ui, R = HD.router, M = HD.modal, t = k => HD.t(k), CS = HD.CONFIG.COIN_SYMBOL;

  // ---------- wallet ----------
  R.add('wallet', { title: 'Wallet', nav: 'wallet', render(v) {
    let tab = 'tx'; const st = HD.state.getState(), TABS = [['tx', 'Transactions'], ['sent', 'Gifts sent'], ['recv', 'Gifts received']];
    v.innerHTML = UI.page(UI.top(t('wallet')) + `<div class="wallet-hero"><div class="muted small">${esc(HD.CONFIG.CURRENCY_NAME)} balance</div><div class="bal" id="w-bal">${CS} ${U.fmt(st.wallet.balance)}</div><div class="small muted">Demo only · no cash value</div></div>
      <div class="quick" style="margin:14px 0"><button data-act="recharge"><span class="q">${icon('plus', 22)}</span>Recharge</button><button data-act="sendGift"><span class="q">${icon('gift', 22)}</span>Send gift</button><button data-act="walletTx"><span class="q">${icon('history', 22)}</span>History</button><button data-go="#rewards"><span class="q">${icon('calendar', 22)}</span>Daily bonus</button></div>
      <div class="tabs" id="w-t" role="tablist"></div><div id="w-b" style="margin-top:12px"></div>`);
    const draw = () => { $('#w-bal', v).textContent = CS + ' ' + U.fmt(st.wallet.balance); $('#w-t', v).innerHTML = TABS.map(x => `<button class="tab ${x[0] === tab ? 'on' : ''}" role="tab" aria-selected="${x[0] === tab}" data-wt="${x[0]}">${x[1]}</button>`).join(''); let h = '';
      const gname = id => st.gifts.find(g => g.id === id) || { icon: '🎁', name: id };
      if (tab === 'tx') h = st.wallet.transactions.length ? `<div class="group">${st.wallet.transactions.slice(0, 60).map(x => `<div class="li"><span class="ic-wrap" style="color:${x.amount < 0 ? 'var(--danger-t)' : 'var(--ok-t)'}">${icon(x.type === 'gift' ? 'gift' : x.type === 'bonus' ? 'calendar' : x.type === 'shop' ? 'star' : 'plus', 20)}</span><span class="grow"><b>${esc(x.label)}</b><div class="faint small">${U.date(x.ts)} · ${U.time(x.ts)}</div></span><b style="color:${x.amount < 0 ? 'var(--danger-t)' : 'var(--ok-t)'}">${x.amount > 0 ? '+' : ''}${U.fmt(x.amount)}</b></div>`).join('')}</div>` : UI.empty('wallet', 'No transactions', '');
      else if (tab === 'sent') h = st.wallet.sent.length ? `<div class="group">${st.wallet.sent.map(g => `<div class="li"><span class="ic-wrap" style="font-size:22px">${gname(g.giftId).icon}</span><span class="grow"><b>${g.qty}× ${esc(gname(g.giftId).name)}</b><div class="faint small">to ${esc(HD.user(g.toId).name)} · ${U.ago(g.ts)}</div></span><b>${CS} ${U.fmt(g.price * g.qty)}</b></div>`).join('')}</div>` : UI.empty('gift', 'No gifts sent yet', 'Send one from a live room.');
      else h = st.wallet.received.length ? `<div class="group">${st.wallet.received.map(g => `<div class="li"><span class="ic-wrap" style="font-size:22px">${gname(g.giftId).icon}</span><span class="grow"><b>${esc(gname(g.giftId).name)}</b><div class="faint small">from ${esc(HD.user(g.fromId).name)} · ${U.ago(g.ts)}</div></span></div>`).join('')}</div>` : UI.empty('gift', 'No gifts received', 'Get on stage — demo listeners may send you one.');
      $('#w-b', v).innerHTML = h; };
    v.addEventListener('click', e => { const b = e.target.closest('[data-wt]'); if (b) { tab = b.dataset.wt; draw(); } }); draw(); return HD.bus.on('wallet', () => R.cur && R.cur.name === 'wallet' && draw());
  } });
  Object.assign(HD.act, { recharge: () => M.requireAccount('add coins') && M.recharge(), sendGift: () => M.gift(null), walletTx: () => { const b = $('[data-wt="tx"]'); b && b.click(); window.scrollTo({ top: document.body.scrollHeight * .4, behavior: 'smooth' }); } });

  // ---------- daily rewards ----------
  R.add('rewards', { title: 'Daily rewards', nav: 'rewards', render(v) {
    const draw = () => { const s = HD.gifts.dailyState(), d = HD.state.getState().daily;
      v.innerHTML = UI.page(UI.top(t('dailyRewards')) + `<div class="card pad center"><div style="font-size:52px">🎁</div><h2>Daily check-in</h2><p class="muted">Come back every day to grow your streak. Day 7 pays the most.</p><div class="days" style="margin:16px 0" role="list">${HD.REWARDS.map((a, i) => { const n = i + 1, done = s.claimedToday ? n <= s.streak : n < s.day, today = !s.claimedToday && n === s.day; return `<div class="day ${done ? 'done' : ''} ${today ? 'today' : ''}" role="listitem" aria-label="Day ${n}, ${a} coins${done ? ', claimed' : ''}"><span>Day ${n}</span><span class="e">${done ? '✅' : n === 7 ? '🎉' : '🪙'}</span><b>${a}</b></div>`; }).join('')}</div>
        <button class="btn primary block" id="claim" ${s.claimedToday ? 'disabled' : ''}>${s.claimedToday ? 'Come back tomorrow' : 'Claim ' + HD.REWARDS[s.day - 1] + ' coins'}</button><p class="faint small" style="margin-top:10px">Streak: ${s.claimedToday ? s.streak : (s.day - 1)} day(s) · progress is saved on this device</p></div>`);
      $('#claim', v).addEventListener('click', () => { if (!M.requireAccount('claim rewards')) return; const r = HD.gifts.claimDaily(); if (!r.ok) return HD.toast.show(r.msg); HD.fx.confetti(); HD.sfx.play('win'); M.open({ title: 'Reward claimed!', body: `<div class="center col" style="align-items:center"><div class="pop" style="font-size:64px">🪙</div><h2>+${U.fmt(r.amt)} demo coins</h2><p class="muted">Day ${r.day} of 7 complete. +25 XP</p></div>`, actions: [{ label: 'Awesome', kind: 'primary' }] }); draw(); });
    }; draw();
  } });

  // ---------- host center ----------
  R.add('host', { title: 'Host center', nav: 'host', render(v) {
    const draw = () => { const st = HD.state.getState(), mine = st.rooms.filter(r => r.mine), hist = st.history.filter(h => h.role === 'host'), listeners = mine.reduce((n, r) => n + (r.peak || 0), 0) + hist.reduce((n, h) => n + h.peak, 0), gifts = mine.reduce((n, r) => n + r.giftsTotal, 0) + hist.reduce((n, h) => n + h.gifts, 0), lvl = HD.progress.info(st.stats.xp).level;
      v.innerHTML = UI.page(UI.top(t('hostCenter')) + `<div class="stats"><div class="stat"><b>${st.stats.roomsHosted}</b><span>Rooms hosted</span></div><div class="stat"><b>${U.short(listeners)}</b><span>Demo listeners</span></div><div class="stat"><b>${U.short(gifts)}</b><span>Demo gifts (${CS})</span></div><div class="stat"><b>${U.short(st.hostEarnings)}</b><span>Demo earnings</span></div><div class="stat"><b>${U.short(HD.social.followerCount())}</b><span>${t('followers')}</span></div><div class="stat"><b>Lv ${lvl}</b><span>Room level</span></div></div>
      <p class="faint small" style="margin-top:8px">Achievements: ${Object.keys(st.achievements).length}/${HD.progress.ACH.length} · all figures are simulated and have no cash value.</p>
      <div class="row" style="margin:16px 0"><button class="btn primary grow" data-go="#create">${icon('plus', 18)} ${t('createRoom')}</button><button class="btn grow" data-go="#history">${icon('history', 18)} ${t('history')}</button></div>
      <section class="sect"><div class="sect-h"><h2>My rooms</h2></div>${mine.length ? `<div class="col">${mine.map(r => UI.roomRow(r) + (r.status === 'ended' ? '<p class="small faint" style="margin:-4px 0 4px 6px">Ended</p>' : '')).join('')}</div>` : UI.empty('mic', 'No rooms yet', 'Rooms you create appear here and in Voice Rooms.')}</section>
      <section class="sect"><div class="sect-h"><h2>Host tools</h2></div><div class="group"><button class="li" data-act="growth"><span class="ic-wrap">${icon('users', 20)}</span><span class="grow"><b>Simulate 25 new followers</b><div class="muted small">Demo tool — unlock follower achievements</div></span></button><button class="li" data-act="growth" data-n="250"><span class="ic-wrap">${icon('users', 20)}</span><span class="grow"><b>Simulate 250 new followers</b><div class="muted small">Demo tool</div></span></button></div></section>
      <section class="sect"><div class="sect-h"><h2>Host rules</h2></div><div class="group" style="padding:12px 14px"><ol style="padding-left:18px;list-style:decimal;color:var(--muted);display:grid;gap:8px"><li>Be welcoming. Harassment, hate and threats are never OK.</li><li>Keep it legal and age-appropriate. No sexual content involving minors, ever.</li><li>Moderate your room — use mute, remove and slow mode.</li><li>Never ask for money, passwords or personal data.</li><li>Real moderation needs a backend team; here it is simulated.</li></ol></div></section>`); };
    draw(); return HD.bus.on('social', () => R.cur && R.cur.name === 'host' && draw());
  } });
  HD.act.growth = ({ n }) => { HD.social.simulateGrowth(+n || 25); HD.toast.ok('+' + (n || 25) + ' followers (simulated)', 'users'); R.refresh(); };

  // ---------- history ----------
  R.add('history', { title: 'Room history', nav: 'host', render(v) {
    const h = HD.state.getState().history;
    v.innerHTML = UI.page(UI.top(t('history'), { actions: h.length ? `<button class="btn sm" data-act="clearHist">Clear</button>` : '' }) + (h.length ? `<div class="col">${h.map(x => `<div class="card pad"><div class="row between"><b>${esc(x.name)}</b><span class="bdg ${x.role === 'host' ? 'host' : ''}">${x.role === 'host' ? 'Hosted' : 'Joined'}</span></div><div class="muted small" style="margin:2px 0 10px">${U.date(x.ts)} · ${U.time(x.ts)}</div><div class="stats four"><div class="stat"><b style="font-size:15px">${U.dur(x.duration)}</b><span>Duration</span></div><div class="stat"><b style="font-size:15px">${U.short(x.peak)}</b><span>Peak</span></div><div class="stat"><b style="font-size:15px">${U.short(x.gifts)}</b><span>Gifts</span></div><div class="stat"><b style="font-size:15px">${x.participants}</b><span>People</span></div></div></div>`).join('')}</div>` : UI.empty('history', 'No history yet', 'Rooms you join or host are logged here, on this device only.')));
  } });
  HD.act.clearHist = async () => { if (await M.confirm('Clear room history?', 'This only affects this device.', { ok: 'Clear', danger: true })) { HD.state.getState().history = []; HD.state.persistState(); R.refresh(); } };

  // ---------- settings ----------
  HD.applySettings = () => { const s = HD.state.getState().settings, de = document.documentElement; const dark = s.theme === 'dark' || (s.theme === 'system' && matchMedia('(prefers-color-scheme: dark)').matches); de.dataset.theme = dark ? 'dark' : 'light'; de.dataset.accent = s.accent; de.dataset.motion = s.motion === 'reduce' ? 'reduce' : s.motion === 'full' ? 'full' : ''; HD.i18n.set(s.language); const m = $('meta[name=theme-color]'); if (m) m.content = dark ? '#08070d' : '#f6f4fb'; };
  R.add('settings', { title: 'Settings', nav: 'settings', render(v) {
    const st = HD.state.getState(), s = st.settings, me = HD.me(); const sw = (k, label, sub, on) => `<label class="sw"><span>${label}${sub ? `<div class="small muted">${sub}</div>` : ''}</span><input type="checkbox" data-k="${k}" ${on ? 'checked' : ''}><span class="t"></span></label>`;
    const seg = (k, opts, cur) => `<div class="tabs" role="radiogroup">${opts.map(o => `<button class="tab ${o[0] === cur ? 'on' : ''}" role="radio" aria-checked="${o[0] === cur}" data-seg="${k}" data-v="${o[0]}">${o[1]}</button>`).join('')}</div>`;
    const draw = () => { v.innerHTML = UI.page(UI.top(t('settings')) + `
      <div class="seg-title">ACCOUNT</div><div class="group"><button class="li" data-go="#editprofile"><span class="ic-wrap">${icon('user', 20)}</span><span class="grow"><b>${esc(me.name)}</b><div class="muted small">@${esc(me.handle)}${me.isGuest ? ' · guest' : ' · local demo account'}</div></span>${icon('chev', 18, 'chev')}</button>${me.isGuest ? `<button class="li" data-go="#register"><span class="ic-wrap">${icon('plus', 20)}</span><span class="grow">Create account</span></button>` : ''}<button class="li" data-act="logout"><span class="ic-wrap">${icon('logout', 20)}</span><span class="grow">${t('logout')}</span></button></div>
      <div class="seg-title">${t('appearance').toUpperCase()}</div><div class="card pad col" style="gap:14px"><div><div class="lbl" style="margin-bottom:8px">Theme</div>${seg('theme', [['dark', 'Dark'], ['light', 'Light'], ['system', 'System']], s.theme)}</div><div><div class="lbl" style="margin-bottom:8px">Accent colour</div><div class="swatches" role="radiogroup" aria-label="Accent colour">${[['purple', '#a56bff'], ['blue', '#4da3ff'], ['pink', '#ff5c9d'], ['gold', '#f5c451'], ['green', '#3ddc97']].map(a => `<button class="swatch ${a[0] === s.accent ? 'on' : ''}" role="radio" aria-checked="${a[0] === s.accent}" aria-label="${a[0]}" data-acc="${a[0]}" style="background:${a[1]}"></button>`).join('')}</div></div><div><div class="lbl" style="margin-bottom:8px">Motion</div>${seg('motion', [['system', 'System'], ['reduce', 'Reduced'], ['full', 'Full']], s.motion)}</div></div>
      <div class="seg-title">${t('notifications').toUpperCase()}</div><div class="group">${sw('notif.follow', 'New followers & friends', '', s.notif.follow)}${sw('notif.gift', 'Gifts', '', s.notif.gift)}${sw('notif.invite', 'Room & host invitations', '', s.notif.invite)}${sw('notif.system', 'System messages', '', s.notif.system)}</div>
      <div class="seg-title">${t('language').toUpperCase()}</div><div class="card pad"><label class="lbl" for="lg">${t('language')}</label><select id="lg" class="input" style="margin-top:6px">${Object.entries(HD.i18n.languages).map(([k, n]) => `<option value="${k}" ${k === s.language ? 'selected' : ''}>${n}</option>`).join('')}</select><p class="faint small" style="margin-top:8px">Navigation and key labels are translated. Untranslated text falls back to English — see js/i18n.js to add more.</p></div>
      <div class="seg-title">PRIVACY</div><div class="group">${sw('privacy.showOnline', 'Show online status', '', s.privacy.showOnline)}${sw('privacy.allowDMs', 'Allow direct messages', '', s.privacy.allowDMs)}${sw('privacy.showHistory', 'Keep room history', '', s.privacy.showHistory)}<button class="li" data-go="#friends" data-blocked><span class="ic-wrap">${icon('ban', 20)}</span><span class="grow">Blocked users (${st.social.blocked.length})</span>${icon('chev', 18, 'chev')}</button></div>
      <div class="seg-title">SAFETY</div><div class="group">${sw('safety.filterChat', 'Filter offensive words in chat', 'Basic client-side filter', s.safety.filterChat)}${sw('safety.hideBlockedInRooms', 'Hide blocked users in rooms', '', s.safety.hideBlockedInRooms)}<button class="li" data-go="#help"><span class="ic-wrap">${icon('shield', 20)}</span><span class="grow">Help & safety</span>${icon('chev', 18, 'chev')}</button></div>
      <div class="seg-title">AUDIO</div><div class="card pad col" style="gap:8px"><label class="lbl" for="av">Output volume · ${s.audio.volume}%</label><input id="av" type="range" min="0" max="100" value="${s.audio.volume}">${sw('audio.sfx', 'Sound effects', 'Join, gift and reward sounds (generated in your browser)', s.audio.sfx)}${sw('audio.echo', 'Echo cancellation', 'Applied next time the mic starts', s.audio.echo)}<button class="btn" data-act="micTest">${icon('mic', 18)} Microphone test</button></div>
      <div class="seg-title">DATA</div><div class="group"><button class="li" data-act="importData"><span class="ic-wrap">${icon('up', 20)}</span><span class="grow">Import a backup (JSON)</span></button><button class="li" data-act="exportData"><span class="ic-wrap">${icon('download', 20)}</span><span class="grow">Export a backup (JSON, with photos & voice notes)</span></button><button class="li" data-act="resetData"><span class="ic-wrap" style="color:var(--danger-t)">${icon('trash', 20)}</span><span class="grow" style="color:var(--danger-t)">Reset all demo data</span></button></div>
      <div class="seg-title">${t('about').toUpperCase()}</div><div class="group"><button class="li" data-go="#about"><span class="ic-wrap">${icon('info', 20)}</span><span class="grow">${t('about')} ${esc(HD.CONFIG.APP_NAME)}</span>${icon('chev', 18, 'chev')}</button><button class="li" data-go="#demo"><span class="ic-wrap">${icon('shield', 20)}</span><span class="grow">Demo mode information</span>${icon('chev', 18, 'chev')}</button></div>`); };
    draw();
    const setK = (k, val) => { const p = k.split('.'); let o = s; while (p.length > 1) o = o[p.shift()]; o[p[0]] = val; HD.state.persistState(); };
    v.addEventListener('change', e => { const el = e.target; if (el.dataset.k) { setK(el.dataset.k, el.checked); HD.toast.show('Saved', { ms: 900 }); } else if (el.id === 'lg') { s.language = el.value; HD.applySettings(); HD.state.persistState(); UI.remountShell(); R.refresh(); } });
    v.addEventListener('input', e => { if (e.target.id === 'av') { s.audio.volume = +e.target.value; HD.audio.setVolume(s.audio.volume); e.target.previousElementSibling.textContent = 'Output volume · ' + s.audio.volume + '%'; HD.state.persistState(); } });
    v.addEventListener('click', e => { const sg = e.target.closest('[data-seg]'), ac = e.target.closest('[data-acc]'); if (sg) { s[sg.dataset.seg] = sg.dataset.v; HD.applySettings(); HD.state.persistState(); draw(); } if (ac) { s.accent = ac.dataset.acc; HD.applySettings(); HD.state.persistState(); draw(); } });
  } });
  UI.remountShell = () => { ['.sidebar', '.bottomnav', '.demo-pill'].forEach(q => { const e = $(q); e && e.remove(); }); UI.mountShell(); const c = R.cur; c && UI.setChrome(c.def, c.params); };
  HD.act.exportData = () => { const s = HD.state.getState(), o = {}; Object.keys(s).forEach(k => { if (k !== 'currentRoom') o[k] = s[k]; }); o._images = Object.assign({}, HD.storage.images); const b = new Blob([JSON.stringify(o)], { type: 'application/json' }), a = document.createElement('a'); a.href = URL.createObjectURL(b); a.download = 'hacktivist-dating-backup.json'; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(a.href), 2000); HD.toast.ok('Backup exported (includes photos & voice notes)', 'download'); };
  HD.act.importData = () => { const inp = document.createElement('input'); inp.type = 'file'; inp.accept = 'application/json,.json'; inp.onchange = async () => { const f = inp.files[0]; if (!f) return; try { const o = JSON.parse(await f.text()); if (!o || !Array.isArray(o.rooms) || !Array.isArray(o.users) || !o.settings || !o.wallet) throw 0; if (!(await M.confirm('Import backup?', 'This replaces the demo data on this device with the file contents.', { ok: 'Import' }))) return; const imgs = o._images || {}; delete o._images; o.v = HD.CONFIG.DATA_VERSION; o.currentRoom = null; HD.rooms.leave(); HD.state.frozen = true; HD.storage.clearImages(); await new Promise(r => setTimeout(r, 150)); await Promise.all(Object.keys(imgs).map(k => HD.storage.putImage(k, imgs[k]))); localStorage.setItem(HD.CONFIG.STORAGE_KEY, JSON.stringify(o)); location.hash = '#home'; location.reload(); } catch (e) { HD.toast.err('That file is not a valid backup'); } }; inp.click(); };
  HD.act.resetData = async () => { if (await M.confirm('Reset all demo data?', 'This deletes your account, rooms, coins, messages and settings on this device and restores the sample data.', { ok: 'Reset everything', danger: true })) { HD.rooms.leave(); HD.state.resetDemoData(); HD.applySettings(); UI.remountShell(); HD.toast.ok('Demo data reset'); location.hash = '#welcome'; R.resolve(); } };

  // ---------- help / about / demo ----------
  R.add('help', { title: 'Help & safety', nav: 'settings', public: true, render(v) {
    const F = [['How do I join a room?', 'Tap any room card. Locked rooms ask for a password (demo rooms use ' + HD.CONFIG.DEMO_ROOM_PASSWORD + ').'], ['How do I speak?', 'Tap Raise hand. In the demo the host usually accepts within a few seconds. Then unmute with the mic button.'], ['Can other people hear me?', 'No. This is a static demo: your microphone is analysed locally for the level meter only, and other participants are simulated.'], ['Are coins real money?', 'No. Demo coins have no value and no payment is ever processed.'], ['How do I try host controls?', 'Create your own room, or open any room → More → Demo: switch my role.'], ['Where is my data?', 'Only in this browser (localStorage / IndexedDB). Clearing site data or using Settings → Reset removes it.']];
    v.innerHTML = UI.page(UI.top(t('help')) + `<div class="note" style="margin-bottom:16px">${icon('shield', 18)}<div>If you or someone else is in danger, contact local emergency services. This demo has no real moderators to help you.</div></div><h2 style="margin-bottom:10px">Safety tips</h2><div class="group" style="padding:12px 14px;margin-bottom:22px"><ul style="display:grid;gap:8px;color:var(--muted);padding-left:16px;list-style:disc"><li>Never share passwords, OTPs, card or bank details in any voice room.</li><li>Keep personal details (address, workplace) private.</li><li>Use Report and Block when someone makes you uncomfortable.</li><li>Be careful with links and “too good to be true” offers.</li><li>Real apps should verify age and provide human moderation.</li></ul></div><h2 style="margin-bottom:10px">FAQ</h2>${F.map(f => `<details class="faq"><summary>${esc(f[0])}</summary><p>${esc(f[1])}</p></details>`).join('')}`);
  } });
  R.add('about', { title: 'About', nav: 'settings', public: true, render(v) {
    v.innerHTML = UI.page(UI.top(t('about')) + `<div class="center col" style="align-items:center;padding:14px 0 24px"><span class="logo-mark hero-mark" style="width:76px;height:76px;font-size:28px;border-radius:26px">&gt;_</span><h1>${esc(HD.CONFIG.APP_NAME)}</h1><p class="muted">${esc(HD.CONFIG.APP_TAGLINE)}</p><span class="bdg demo">v${esc(HD.CONFIG.APP_VERSION)} · DEMO</span></div>
      <div class="group"><button class="li" data-go="#demo"><span class="ic-wrap">${icon('info', 20)}</span><span class="grow">What “demo mode” means</span>${icon('chev', 18, 'chev')}</button><button class="li" data-act="installApp"><span class="ic-wrap">${icon('download', 20)}</span><span class="grow">Install as an app</span></button><button class="li" data-go="#help"><span class="ic-wrap">${icon('help', 20)}</span><span class="grow">${t('help')}</span></button></div><p class="faint small center" style="margin-top:18px">A frontend-only social-audio demo. No trademarks or assets from other apps are used. MIT licensed.</p>`);
  } });
  HD.act.installApp = async () => { const p = HD.installPrompt; if (p) { p.prompt(); await p.userChoice; HD.installPrompt = null; } else M.alert('Install the app', 'Use your browser menu → “Install app” / “Add to Home Screen”. (Requires HTTPS, e.g. GitHub Pages.)'); };
  R.add('demo', { title: 'Demo mode', nav: 'settings', public: true, render(v) {
    v.innerHTML = UI.page(UI.top('Demo mode') + `<div class="note" style="margin-bottom:16px">${icon('info', 18)}<div><b>This is a frontend-only demonstration.</b> Live multi-user communication, real authentication, real payments and server-side moderation require backend services.</div></div>
      <div class="group" style="padding:6px 14px"><div class="li"><span class="ic-wrap">${icon('mic', 20)}</span><span class="grow"><b>Voice</b><div class="muted small">Your mic is real (permission, mute, level meter) but never transmitted. Other speakers are simulated.</div></span></div><div class="li"><span class="ic-wrap">${icon('user', 20)}</span><span class="grow"><b>Accounts</b><div class="muted small">Local demo accounts. Any password works; none is stored.</div></span></div><div class="li"><span class="ic-wrap">${icon('wallet', 20)}</span><span class="grow"><b>Coins & gifts</b><div class="muted small">Fake coins with no value. No payments.</div></span></div><div class="li"><span class="ic-wrap">${icon('lock', 20)}</span><span class="grow"><b>Locks & permissions</b><div class="muted small">Room passwords and roles are browser-side UI rules, not security.</div></span></div><div class="li"><span class="ic-wrap">${icon('shield', 20)}</span><span class="grow"><b>Moderation</b><div class="muted small">Reports are stored locally. Nobody reviews them.</div></span></div><div class="li"><span class="ic-wrap">${icon('trophy', 20)}</span><span class="grow"><b>Leaderboards & people</b><div class="muted small">Generated fictional data. No real users.</div></span></div></div>
      <p class="muted small" style="margin-top:14px">Read docs/SECURITY.md and docs/REALTIME.md in the project for the full explanation and the path to a real backend.</p>`);
  } });
})();
