/* Screens: profile, edit profile, friends, following, followers, messages, notifications, leaderboard */
(function () {
  const HD = window.HD, U = HD.utils, { esc, icon, $, $$ } = U, UI = HD.ui, R = HD.router, M = HD.modal, t = k => HD.t(k);
  const MEDALS = n => n === 1 ? 'r1' : n === 2 ? 'r2' : n === 3 ? 'r3' : '';

  // ---------- profile ----------
  R.add('profile', { title: 'Profile', nav: 'profile', render(v, [uid]) {
    const st = HD.state.getState(), self = !uid || uid === 'me', u = self ? HD.me() : HD.user(uid); let tab = 'posts';
    const info = HD.progress.info(self ? st.stats.xp : u.level * 220), fc = self ? HD.social.followerCount() : u.followers, likes = self ? st.stats.likes + (u.likes || 0) : u.likes;
    const hosted = st.rooms.filter(r => r.hostId === u.id), rnd = U.rng('p' + u.id);
    const TABS = [['posts', 'Posts'], ['moments', 'Moments'], ['rooms', 'Rooms'], ['gifts', 'Gifts'], ['ach', 'Achievements']];
    const actions = self ? `<div class="row" style="justify-content:center;margin-top:12px"><button class="btn sm" data-go="#editprofile">${icon('edit', 15)} Edit profile</button><button class="btn sm" data-go="#settings">${icon('settings', 15)} ${t('settings')}</button></div>` : `<div class="row" style="justify-content:center;margin-top:12px">${UI.followBtn(u.id)}<button class="btn sm" data-act="dmUser" data-id="${u.id}">${t('messages')}</button><button class="btn sm" data-act="friendUser" data-id="${u.id}">${HD.social.isFriend(u.id) ? 'Friends ✓' : HD.social.isPending(u.id) ? 'Requested' : 'Add friend'}</button><button class="icon-btn" data-act="userMenu" data-id="${u.id}" aria-label="More">${icon('more', 18)}</button></div>`;
    v.innerHTML = UI.page(`<div class="profile-hero ${u.flash || (self && HD.vip.has('flash')) ? 'flash' : ''}"><div class="cover" style="background-image:url('${U.cover('pf' + u.id)}')"></div>${self ? '' : `<button class="icon-btn" data-back aria-label="Back" style="position:absolute;left:0;top:10px">${icon('back')}</button>`}
      <span class="avw${u.frame ? ' frame-' + u.frame : ''}" style="--s:96px;margin-top:20px"><img class="av" src="${HD.userAvatar(u)}" alt="" style="border-width:4px"></span>
      <h1 style="margin-top:10px"><span class="${HD.cosmetic.nameCls(u.id)}" style="${HD.cosmetic.nameStyle(u.id)}">${esc(u.name)}</span>${UI.vf(u)}</h1><div class="row wrap" style="justify-content:center;gap:6px;margin-top:6px">${UI.tierPill(u.tier)} ${UI.presPill(u.prestige)} ${u.title ? UI.titleBadge(u.title.id || u.title, u.title.tier) : ''}</div><div class="muted small">@${esc(u.handle)} · ID ${esc(HD.displayId(u))} · ${u.flag} ${esc(u.country)}</div>
      <div class="row wrap" style="justify-content:center;margin:8px 0"><span class="lvl">${icon('bolt', 13)} Level ${info.level}</span>${u.vip ? '<span class="bdg vip">VIP</span>' : ''}${u.isGuest ? '<span class="bdg">Guest</span>' : ''}</div><p class="muted" style="max-width:440px;margin:0 auto">${esc(u.bio)}</p>${(u.interests || []).length ? `<div style="margin-top:10px">${UI.interestTags(u, self ? null : HD.me())}</div>` : ''}${self ? '' : `<div class="bdg host" style="margin-top:6px">${HD.demo.compat(HD.me(), u)}% compatible with you</div>`}${actions}</div>
      <div class="stats ${self ? 'five' : 'four'}" style="margin-top:14px"><button class="stat" data-go="#followers${self ? '' : ''}"><b>${U.short(fc)}</b><span>${t('followers')}</span></button><button class="stat" data-go="#following"><b>${U.short(self ? st.social.following.length : u.following)}</b><span>${t('following')}</span></button><div class="stat"><b>${U.short(likes)}</b><span>Likes</span></div><div class="stat"><b>${self ? st.stats.roomsHosted : u.roomsHosted}</b><span>Hosted</span></div>${self ? `<button class="stat" data-go="#visitors"><b>${U.short(st.stats.visitors || 0)}</b><span>Visitors</span></button>` : ''}</div>
      <div class="card pad" style="margin-top:12px"><div class="row between"><b>XP ${U.fmt(info.xp)}</b><span class="muted small">${self ? U.fmt(info.next - info.xp) + ' XP to level ' + (info.level + 1) : 'Gifts received: ' + U.fmt(self ? st.stats.giftsReceived : u.giftsReceived)}</span></div><div class="bar" style="margin-top:8px" role="progressbar" aria-valuenow="${info.pct}" aria-valuemin="0" aria-valuemax="100" aria-label="Level progress"><i style="width:${info.pct}%"></i></div></div>
      ${self ? `<div class="card pad" style="margin-top:14px"><div class="row between" style="margin-bottom:10px"><b>${t('wallet')}</b><button class="coin" data-go="#wallet" aria-label="Open wallet">${HD.CONFIG.COIN_SYMBOL} ${U.fmt(st.wallet.balance)}</button></div><div class="row"><button class="hub-card" data-go="#vip" style="--tc:#f5c451"><b>VIP</b><span class="small">${HD.vip.tier() ? HD.vip.tier().name : 'Activate'}</span><i>${HD.vip.tier() ? HD.vip.tier().emoji : '👑'}</i></button><button class="hub-card" data-go="#prestige" style="--tc:#ff8a5b"><b>Prestige</b><span class="small">${HD.prestige.level() ? 'Level ' + HD.prestige.level() : 'Start'}</span><i>🏛️</i></button></div></div>
      <div class="card pad hubgrid" style="margin-top:12px">${[['ach', 'trophy', 'Achievement'], ['#influence', 'bolt', 'Influence'], ['#gamelevel', 'trophy', 'Game level'], ['#missions', 'calendar', 'Missions'], ['#mystery', 'eye', 'Mystery'], ['#shop', 'star', 'Props store'], ['#specialid', 'shield', 'Special ID'], ['#titles', 'crown', 'Title']].map(x => x[0] === 'ach' ? `<button data-act="goAch"><span class="q">${icon(x[1], 22)}</span>${x[2]}</button>` : `<button data-go="${x[0]}"><span class="q">${icon(x[1], 22)}</span>${x[2]}</button>`).join('')}</div>
      <div class="group" style="margin-top:12px">${[['cp', 'heart', 'CP space'], ['family', 'users', 'Family'], ['moments', 'compass', 'Moments'], ['matches', 'heart', t('matches')], ['rewards', 'calendar', t('dailyRewards')], ['host', 'mic', t('hostCenter')], ['history', 'history', t('history')], ['friends', 'users', t('friends')], ['leaderboard', 'trophy', t('leaderboard')], ['help', 'help', t('help')], ['about', 'info', t('about')]].map(x => `<button class="li" data-go="#${x[0]}"><span class="ic-wrap">${icon(x[1], 20)}</span><span class="grow">${x[2]}</span>${icon('chev', 18, 'chev')}</button>`).join('')}<button class="li" data-act="logout"><span class="ic-wrap" style="color:var(--danger-t)">${icon('logout', 20)}</span><span class="grow" style="color:var(--danger-t)">${t('logout')}</span></button></div>` : ''}
      <div class="tabs" style="margin-top:18px" role="tablist" id="p-tabs"></div><div id="p-body" style="margin-top:14px"></div>`);
    const body = () => {
      $('#p-tabs', v).innerHTML = TABS.map(x => `<button class="tab ${x[0] === tab ? 'on' : ''}" role="tab" aria-selected="${x[0] === tab}" data-pt="${x[0]}">${x[1]}</button>`).join(''); let h = '';
      if (tab === 'posts') { const SEED = ['Just wrapped a two-hour room and my voice is gone. Worth it.', 'Hot take: every good conversation starts with a bad joke.', 'Looking for a study buddy for night sessions 📚', 'New playlist drop in the lounge tonight 🎧'];
        const posts = self ? st.posts : [0, 1].map(i => ({ id: i, text: SEED[(u.id.length + i * 2 + u.level) % SEED.length], ts: Date.now() - (i + 1) * 864e5 * (1 + rnd() * 3), likes: 3 + (rnd() * 90 | 0) }));
        h = (self ? `<form id="pf" class="row" style="margin-bottom:12px"><input class="input grow" id="pt" maxlength="200" placeholder="Share something…" aria-label="New post"><button class="btn primary sm" type="submit">Post</button></form>` : '') + (posts.length ? posts.map(p => `<div class="post"><p>${esc(p.text)}</p><div class="row between muted small" style="margin-top:8px"><span>${U.ago(p.ts)}</span><span>${icon('heart', 13)} ${p.likes}</span></div></div>`).join('') : UI.empty('edit', 'No posts yet', 'Share your first thought above.')); }
      else if (tab === 'moments') h = `<div class="moments">${Array.from({ length: 9 }, (_, i) => `<div style="background-image:url('${U.cover(u.id + 'm' + i)}')" role="img" aria-label="Moment ${i + 1}"></div>`).join('')}</div>`;
      else if (tab === 'rooms') h = hosted.length ? `<div class="col">${hosted.filter(r => r.status === 'live').map(UI.roomRow).join('')}</div>` : UI.empty('mic', 'No rooms hosted yet', self ? 'Create a room to see it here.' : '', self ? '<button class="btn primary" data-go="#create">Create room</button>' : '');
      else if (tab === 'gifts') { const recv = self ? st.wallet.received : []; const tally = {}; (self ? recv.map(g => g.giftId) : ['rose', 'heart', 'coffee', 'star', 'balloon', 'crown'].slice(0, 2 + (u.level % 4))).forEach(g => tally[g] = (tally[g] || 0) + (self ? 1 : 1 + (rnd() * 20 | 0))); const ks = Object.keys(tally); h = ks.length ? `<div class="gifts">${ks.map(k => { const g = st.gifts.find(x => x.id === k); return `<div class="gift"><span class="e">${g.icon}</span><b>${esc(g.name)}</b><span>×${tally[k]}</span></div>`; }).join('')}</div>` : UI.empty('gift', 'No gifts received', 'Speak on stage — bots may send you one!'); }
      else h = `<div class="col">${HD.progress.ACH.map(a => { const ok = self ? !!st.achievements[a.id] : (U.hash(u.id + a.id) % 3 !== 0); return `<div class="ach ${ok ? '' : 'lock'}"><div class="e">${a.icon}</div><div class="grow"><b>${a.title}</b> ${ok ? '' : icon('lock', 13)}<div class="muted small">${a.desc}</div></div><span class="bdg ${ok ? 'host' : ''}">${ok ? 'Unlocked' : '+' + a.xp + ' XP'}</span></div>`; }).join('')}</div>`;
      $('#p-body', v).innerHTML = h; const f = $('#pf', v); if (f) f.addEventListener('submit', e => { e.preventDefault(); const x = $('#pt', v).value.trim(); if (!x) return; st.posts.unshift({ id: U.uid('p'), text: x, ts: Date.now(), likes: 0 }); HD.state.persistState(); HD.toast.ok('Posted'); body(); });
    };
    v.addEventListener('click', e => { const b = e.target.closest('[data-pt]'); if (b) { tab = b.dataset.pt; body(); } }); body();
  } });
  HD.act.goAch = () => { const b = document.querySelector('[data-pt=ach]'); if (b) { b.click(); b.scrollIntoView({ behavior: 'smooth', block: 'center' }); } };
  HD.act.dmUser = ({ id }) => { if (M.requireAccount('send messages')) R.go('#messages/' + id); };
  HD.act.friendUser = ({ id }) => { if (!M.requireAccount('add friends')) return; if (HD.social.isFriend(id)) { HD.social.removeFriend(id); HD.toast.show('Friend removed'); } else if (!HD.social.isPending(id)) { HD.social.addFriend(id); HD.toast.ok('Friend request sent', 'users'); } R.refresh(); };
  HD.act.userMenu = ({ id }) => { const b = HD.social.isBlocked(id); M.open({ title: 'More', body: `<div class="group"><button class="li" data-k="report"><span class="ic-wrap">${icon('flag', 20)}</span><span class="grow">Report user</span></button><button class="li" data-k="block"><span class="ic-wrap">${icon('ban', 20)}</span><span class="grow">${b ? 'Unblock' : 'Block'} user</span></button></div>`, onOpen: h => h.el.addEventListener('click', e => { const k = (e.target.closest('[data-k]') || {}).dataset; if (!k) return; h.close(); setTimeout(() => { if (k.k === 'report') M.report('user', id, HD.user(id).name); else if (b) { HD.social.unblock(id); HD.toast.ok('Unblocked'); R.refresh(); } else M.block(id).then(ok => ok && R.go('#home')); }, 230); }) }); };

  // ---------- edit profile ----------
  R.add('editprofile', { title: 'Edit profile', nav: 'profile', render(v) {
    const me = HD.me(); let img = null;
    v.innerHTML = UI.page(UI.top('Edit profile') + `<form id="ef" novalidate><div class="center" style="margin:6px 0 18px"><span class="avw" style="--s:96px"><img class="av" id="e-av" src="${HD.userAvatar(me)}" alt=""></span><div class="row" style="justify-content:center;margin-top:10px"><label class="btn sm" for="e-f" style="cursor:pointer">Change photo</label><button type="button" class="btn sm ghost" id="e-rm">Remove</button></div><input id="e-f" type="file" accept="image/*" class="sr-only"></div>
      <div class="field"><label for="e-n">Display name</label><input id="e-n" class="input" maxlength="24" value="${esc(me.name)}"></div><div class="field"><label for="e-h">Username</label><input id="e-h" class="input" maxlength="20" value="${esc(me.handle)}"></div>
      <div class="field"><label for="e-c">Country</label><select id="e-c" class="input">${['India', 'UAE', 'UK', 'USA', 'Germany', 'Brazil', 'Japan', 'Kenya', 'Turkey', 'Spain', 'Canada', 'Singapore'].map(c => `<option ${c === me.country ? 'selected' : ''}>${c}</option>`).join('')}</select></div>
      <div class="field"><label for="e-b">Bio</label><textarea id="e-b" class="input" maxlength="120">${esc(me.bio)}</textarea></div>
      ${UI.interestEditor(me)}<div class="group" style="margin-bottom:16px"><label class="sw"><span>Demo VIP badge<div class="small muted">Cosmetic only — for previewing the UI</div></span><input type="checkbox" id="e-v" ${me.vip ? 'checked' : ''}><span class="t"></span></label></div><button class="btn primary block" type="submit">${t('save')}</button></form>`);
    const getInts = UI.bindInterestEditor($('#e-int', v), me);
    $('#e-f', v).addEventListener('change', async e => { const f = e.target.files[0]; if (!f) return; try { img = await U.resizeImage(f, 256); $('#e-av', v).src = img; } catch (x) { HD.toast.err('Could not read that image'); } });
    $('#e-rm', v).addEventListener('click', () => { img = false; $('#e-av', v).src = U.avatar(me.seed, $('#e-n', v).value); });
    $('#ef', v).addEventListener('submit', e => { e.preventDefault(); const n = $('#e-n', v).value.trim(); if (!n) return HD.toast.err('Name cannot be empty');
      Object.assign(me, { name: n, handle: $('#e-h', v).value.trim().toLowerCase().replace(/[^a-z0-9_]/g, '_') || me.handle, country: $('#e-c', v).value, bio: $('#e-b', v).value.trim(), vip: $('#e-v', v).checked, interests: getInts() }); me.flag = { India: '🇮🇳', UAE: '🇦🇪', UK: '🇬🇧', USA: '🇺🇸', Germany: '🇩🇪', Brazil: '🇧🇷', Japan: '🇯🇵', Kenya: '🇰🇪', Turkey: '🇹🇷', Spain: '🇪🇸', Canada: '🇨🇦', Singapore: '🇸🇬' }[me.country] || '🌍';
      if (img) HD.storage.putImage('av:me', img); else if (img === false) HD.storage.delImage('av:me'); const s = HD.state.getState(); s.account = s.currentUser.isGuest ? s.account : me; HD.state.persistState(); HD.toast.ok('Profile updated'); R.go('#profile'); });
  } });

  // ---------- friends / following / followers ----------
  const listScreen = (name, title, get, opts = {}) => R.add(name, { title, nav: 'profile', render(v) {
    const draw = () => { const ids = get(), st = HD.state.getState(); v.innerHTML = UI.page(UI.top(title) + (opts.extra ? opts.extra(st) : '') + (ids.length ? `<div class="group">${ids.map(id => UI.userRow(HD.user(id), opts.right ? opts.right(id) : UI.followBtn(id))).join('')}</div>` : UI.empty(opts.icon || 'users', opts.empty || 'Nobody here yet', opts.hint || ''))); };
    draw(); const off = HD.bus.on('social', () => { if (R.cur && R.cur.name === name) draw(); }); return off;
  } });
  listScreen('following', t('following'), () => HD.state.getState().social.following.filter(x => !HD.social.isBlocked(x)), { empty: 'Not following anyone', hint: 'Follow hosts to see their rooms first.' });
  listScreen('followers', t('followers'), () => HD.state.getState().social.followers.filter(x => !HD.social.isBlocked(x)), { empty: 'No followers yet', hint: 'Host a room to get discovered.' });
  R.add('friends', { title: 'Friends', nav: 'profile', render(v) {
    let tab = 'friends'; const TABS = [['friends', 'Friends'], ['req', 'Requests'], ['sug', 'Suggested'], ['blocked', 'Blocked']];
    const draw = () => { const st = HD.state.getState(), so = st.social; let ids, right, empty;
      if (tab === 'friends') { ids = st.friends; right = id => `<button class="btn sm" data-act="dmUser" data-id="${id}">${t('messages')}</button><button class="icon-btn" style="width:34px;height:34px" data-act="rmFriend" data-id="${id}" aria-label="Remove friend">${icon('close', 15)}</button>`; empty = 'No friends yet'; }
      else if (tab === 'req') { ids = so.requests; right = id => `<button class="btn sm primary" data-act="okReq" data-id="${id}">Accept</button><button class="btn sm" data-act="noReq" data-id="${id}">Decline</button>`; empty = 'No pending requests'; }
      else if (tab === 'sug') { ids = st.users.filter(u => !st.friends.includes(u.id) && !so.requests.includes(u.id) && !so.blocked.includes(u.id)).slice(0, 12).map(u => u.id); right = id => `<button class="btn sm ${HD.social.isPending(id) ? '' : 'primary'}" data-act="addF" data-id="${id}" ${HD.social.isPending(id) ? 'disabled' : ''}>${HD.social.isPending(id) ? 'Requested' : 'Add'}</button>`; empty = 'No suggestions'; }
      else { ids = so.blocked; right = id => `<button class="btn sm" data-act="unblock" data-id="${id}">Unblock</button>`; empty = 'No blocked users'; }
      v.innerHTML = UI.page(UI.top(t('friends')) + `<div class="tabs" role="tablist">${TABS.map(x => `<button class="tab ${x[0] === tab ? 'on' : ''}" role="tab" aria-selected="${x[0] === tab}" data-ft="${x[0]}">${x[1]}${x[0] === 'req' && so.requests.length ? ` (${so.requests.length})` : ''}</button>`).join('')}</div><div style="margin-top:14px">${ids.length ? `<div class="group">${ids.map(id => UI.userRow(HD.user(id), `<span class="row" style="gap:6px">${right(id)}</span>`)).join('')}</div>` : UI.empty('users', empty, '')}</div>`); };
    v.addEventListener('click', e => { const b = e.target.closest('[data-ft]'); if (b) { tab = b.dataset.ft; draw(); } }); draw(); return HD.bus.on('social', () => { if (R.cur && R.cur.name === 'friends') draw(); });
  } });
  Object.assign(HD.act, { rmFriend: ({ id }) => { HD.social.removeFriend(id); HD.toast.show('Friend removed'); }, okReq: ({ id }) => { HD.social.acceptRequest(id); HD.toast.ok('Friend added', 'users'); }, noReq: ({ id }) => { HD.social.declineRequest(id); HD.toast.show('Request declined'); }, addF: ({ id }) => { if (!M.requireAccount('add friends')) return; HD.social.addFriend(id); HD.toast.ok('Friend request sent', 'users'); }, unblock: ({ id }) => { HD.social.unblock(id); HD.toast.ok('Unblocked'); } });

  // ---------- messages ----------
  R.add('messages', { title: 'Messages', nav: 'messages', render(v, [uid]) { return uid ? thread(v, uid) : inbox(v); } });
  function inbox(v) {
    const draw = () => { const cs = HD.messages.conversations(), st = HD.state.getState();
      v.innerHTML = UI.page(`<header class="topbar"><h1>${t('messages')}</h1><button class="icon-btn" data-act="newDM" aria-label="New message">${icon('edit', 19)}</button></header><div class="note" style="margin-bottom:12px">${icon('info', 18)}<div>Local demo messages. Contacts are simulated and replies are scripted.</div></div>` + (cs.length ? `<div class="group">${cs.map(c => { const u = HD.user(c.userId), ms = HD.messages.thread(c.userId), l = ms[ms.length - 1]; return `<button class="li" data-go="#messages/${c.userId}">${UI.av(u, { s: 50, online: true })}<span class="grow"><b>${esc(u.name)}</b><div class="muted small trunc">${l ? (l.from === 'me' ? 'You: ' : '') + (l.audio ? '🎤 Voice note' : esc(l.text)) : 'Say hi'}</div></span><span class="col" style="align-items:flex-end;gap:4px"><span class="faint tiny">${U.ago(c.last)}</span>${c.unread ? `<span class="ub">${c.unread}</span>` : ''}</span></button>`; }).join('')}</div>` : UI.empty('chat', 'No conversations', 'Start one with the pencil button.'))); };
    draw(); return HD.bus.on('dm', () => { if (R.cur && R.cur.name === 'messages' && !R.cur.params[0]) draw(); });
  }
  HD.act.newDM = () => { if (!M.requireAccount('send messages')) return; const st = HD.state.getState(), l = st.users.filter(u => !st.social.blocked.includes(u.id)).slice(0, 14);
    M.open({ title: 'New message', body: `<div class="group">${l.map(u => `<button class="li" data-u="${u.id}">${UI.av(u, { s: 40 })}<span class="grow"><b>${esc(u.name)}</b><div class="muted small">@${esc(u.handle)}</div></span></button>`).join('')}</div>`, onOpen: h => h.el.addEventListener('click', e => { const b = e.target.closest('[data-u]'); if (b) { h.close(); R.go('#messages/' + b.dataset.u); } }) }); };
  function thread(v, uid) {
    if (HD.me().isGuest) { v.innerHTML = UI.page(UI.top(t('messages')) + UI.empty('chat', 'Account needed', 'Create a free local demo account to send messages.', '<button class="btn primary" data-go="#register">Create account</button>')); return; } const u = HD.user(uid); UI.thread = uid; HD.messages.ensure(uid); HD.messages.markRead(uid); let typing = false, sel = null;
    v.innerHTML = UI.page(`<header class="topbar"><button class="icon-btn" data-back aria-label="Back">${icon('back')}</button><h1 class="sr-only">Chat with ${esc(u.name)}</h1><button class="row grow" data-user="${uid}" style="text-align:left">${UI.av(u, { s: 38, online: true })}<div><b>${esc(u.name)}</b><div class="tiny muted" id="t-st">${u.online ? 'online' : 'offline'}</div></div></button></header><div id="th" role="log" aria-live="polite" style="min-height:50vh"></div><form class="composer" id="tf"><button type="button" class="icon-btn" id="ib" aria-label="Icebreaker" title="Icebreaker">🧊</button><input class="input grow" id="ti" maxlength="500" placeholder="Message ${esc(u.name)}…" aria-label="Message" autocomplete="off"><div class="rec" id="rc" hidden><i></i><span id="rt">0:00</span><span class="small grow">Recording…</span><button type="button" class="icon-btn" id="rx" aria-label="Cancel recording" style="width:32px;height:32px">${icon('trash', 15)}</button></div>${HD.voice.supported ? `<button type="button" class="icon-btn" id="vr" aria-label="Record voice note">${icon('mic', 18)}</button>` : ''}<button class="icon-btn" type="submit" aria-label="Send" style="background:linear-gradient(120deg,var(--accent),var(--accent2));color:var(--accent-ink)">${icon('send', 18)}</button></form>`);
    const draw = () => { const ms = HD.messages.thread(uid); $('#th', v).innerHTML = ms.map(m => { const me = m.from === 'me', rx = Object.keys(m.reactions || {}); return `<div class="mrow ${me ? 'me' : ''}">${me ? '' : UI.av(u, { s: 28 })}<div style="max-width:78%"><div class="bubble" data-mid="${m.id}" tabindex="0" role="button" aria-label="Message, tap to react" style="max-width:100%;cursor:pointer">${m.audio ? `<div class="vnote">🎤<audio controls preload="none" src="${HD.storage.images[m.audio] || ''}" aria-label="Voice note, ${m.dur || 0} seconds"></audio></div>` : esc(m.text)}<small>${U.time(m.ts)}${m.audio ? ' · ' + (m.dur || 0) + 's' : ''}</small></div>${rx.length ? `<span class="rx">${rx.map(e => e + (m.reactions[e].length > 1 ? m.reactions[e].length : '')).join(' ')}</span>` : ''}${sel === m.id ? `<div class="picker-emoji">${['❤️', '😂', '👍', '🔥', '😮'].map(e => `<button data-re="${e}" aria-label="React ${e}">${e}</button>`).join('')}</div>` : ''}</div></div>`; }).join('') + (typing ? `<div class="mrow">${UI.av(u, { s: 28 })}<div class="bubble typing" aria-label="typing"><i></i><i></i><i></i></div></div>` : ''); window.scrollTo(0, document.body.scrollHeight); };
    draw();
    if (UI.dmPrefill) { $('#ti', v).value = UI.dmPrefill; UI.dmPrefill = null; }
    $('#ib', v).addEventListener('click', () => { $('#ti', v).value = HD.icebreaker.next(); $('#ti', v).focus(); });
    let timer = null; const recUI = on => { $('#rc', v).hidden = !on; $('#ti', v).hidden = on; $('#ib', v).hidden = on; const b = $('#vr', v); if (b) { b.innerHTML = on ? icon('send', 18) : icon('mic', 18); b.setAttribute('aria-label', on ? 'Send voice note' : 'Record voice note'); } };
    const vr = $('#vr', v); if (vr) { vr.addEventListener('click', async () => { if (HD.voice.rec) { clearInterval(timer); recUI(false); const r = await HD.voice.stop(); if (r && r.dur >= 1) HD.messages.sendVoice(uid, r.dataUrl, r.dur); else HD.toast.show('Too short — hold a little longer'); return; } if (!(await HD.voice.start())) return HD.toast.err('Microphone unavailable or permission denied'); recUI(true); timer = setInterval(() => { const s = Math.round((Date.now() - HD.voice.t0) / 1000); $('#rt', v).textContent = (s / 60 | 0) + ':' + String(s % 60).padStart(2, '0'); if (s >= 60) vr.click(); }, 500); });
      $('#rx', v).addEventListener('click', () => { clearInterval(timer); HD.voice.cancel(); recUI(false); }); }
    $('#tf', v).addEventListener('submit', e => { e.preventDefault(); const i = $('#ti', v); if (HD.messages.sendDM(uid, i.value).ok) i.value = ''; });
    v.addEventListener('click', e => { const re = e.target.closest('[data-re]'); if (re) { HD.messages.reactDM(sel, re.dataset.re); sel = null; return; } const b = e.target.closest('[data-mid]'); if (b) { sel = sel === b.dataset.mid ? null : b.dataset.mid; draw(); } });
    const o1 = HD.bus.on('dm', d => { if (d && d.incoming && d.uid === uid) HD.messages.markRead(uid); draw(); }), o2 = HD.bus.on('dm:typing', d => { if (d.uid === uid) { typing = d.on; $('#t-st', v) && ($('#t-st', v).textContent = d.on ? 'typing…' : 'online'); draw(); } });
    return () => { o1(); o2(); UI.thread = null; clearInterval(timer); HD.voice.cancel(); };
  }

  // ---------- notifications ----------
  R.add('notifications', { title: 'Notifications', nav: 'notifications', render(v) {
    const ICON = { follow: 'user', friend: 'users', gift: 'gift', invite: 'mic', host: 'crown', achievement: 'trophy', reward: 'calendar', system: 'info' };
    const draw = () => { const l = HD.notify.list(); v.innerHTML = UI.page(UI.top(t('notifications'), { actions: `<button class="btn sm" data-act="readAll">Mark all read</button>` }) + (l.length ? `<div class="col" style="gap:2px">${l.map(n => `<div class="nt ${n.read ? '' : 'unread'}" data-nid="${n.id}" role="button" tabindex="0"><span class="ic-wrap li" style="width:40px;height:40px;padding:0;justify-content:center;flex:none;background:var(--surface2);color:var(--accent-t);border-radius:14px">${icon(ICON[n.type] || 'bell', 20)}</span><div class="grow"><div>${n.from ? `<b>${esc(HD.user(n.from).name)}</b> ` : ''}${esc(n.text)}</div><div class="faint tiny">${U.ago(n.ts)}${n.read ? '' : ' · new'}</div></div><button class="icon-btn" style="width:34px;height:34px" data-del="${n.id}" aria-label="Delete notification">${icon('trash', 15)}</button></div>`).join('')}</div>` : UI.empty('bell', 'All caught up', 'New follows, gifts and invitations show up here.'))); };
    draw();
    v.addEventListener('click', e => { const d = e.target.closest('[data-del]'); if (d) { HD.notify.remove(d.dataset.del); draw(); return; } const n = e.target.closest('[data-nid]'); if (!n) return; const it = HD.state.getState().notifications.find(x => x.id === n.dataset.nid); HD.notify.markRead(n.dataset.nid); if (it.roomId && HD.room(it.roomId)) R.go('#room/' + it.roomId); else if (it.type === 'reward') R.go('#rewards'); else if (it.type === 'achievement') R.go('#profile'); else if (it.from && (it.type === 'follow' || it.type === 'friend')) R.go('#profile/' + it.from); else if (it.type === 'gift') R.go('#wallet'); else draw(); });
    HD.act.readAll = () => { HD.notify.markAll(); draw(); HD.toast.show('All marked as read'); }; return HD.bus.on('notif', () => { if (R.cur && R.cur.name === 'notifications') draw(); });
  } });

  // ---------- leaderboard ----------
  R.add('leaderboard', { title: 'Leaderboard', nav: 'leaderboard', render(v) {
    let per = 'daily', cat = 'hosts'; const P = [['daily', 'Daily'], ['weekly', 'Weekly'], ['monthly', 'Monthly']], C = [['hosts', 'Top Hosts'], ['gifters', 'Top Gifters'], ['receivers', 'Top Receivers'], ['speakers', 'Top Speakers']], unit = { hosts: 'rooms', gifters: HD.CONFIG.COIN_SYMBOL, receivers: HD.CONFIG.COIN_SYMBOL, speakers: 'min' };
    v.innerHTML = UI.page(UI.top(t('leaderboard')) + `<div class="note" style="margin-bottom:12px">${icon('info', 18)}<div><b>Demo rankings.</b> Generated sample data — not real users or real scores.</div></div><div class="tabs" id="l-p" role="tablist"></div><div class="hscroll noscroll-x" style="margin-top:12px" id="l-c"></div><div id="l-b"></div>`);
    const draw = () => { $('#l-p', v).innerHTML = P.map(x => `<button class="tab ${x[0] === per ? 'on' : ''}" role="tab" aria-selected="${x[0] === per}" data-p="${x[0]}">${x[1]}</button>`).join(''); $('#l-c', v).innerHTML = UI.chips(C, cat, 'data-c'); const l = HD.demo.leaderboard(per, cat), pd = (e, n) => { const u = HD.user(e.userId); return `<button class="pd ${n === 1 ? 'first' : ''}" data-user="${u.id}"><span class="rank ${MEDALS(n)}" style="font-size:${n === 1 ? 26 : 20}px">${n === 1 ? '🥇' : n === 2 ? '🥈' : '🥉'}</span>${UI.av(u, { s: n === 1 ? 64 : 52 })}<b class="trunc" style="max-width:100%">${esc(u.name)}</b><span class="small muted">${U.short(e.score)} ${unit[cat]}</span></button>`; };
      $('#l-b', v).innerHTML = `<div class="podium" style="margin-top:14px">${pd(l[1], 2)}${pd(l[0], 1)}${pd(l[2], 3)}</div><div class="group">${l.slice(3).map((e, i) => { const u = HD.user(e.userId); return `<div class="li" data-user="${u.id}" role="button" tabindex="0" style="cursor:pointer"><span class="rank">${i + 4}</span>${UI.av(u, { s: 40 })}<span class="grow"><b>${esc(u.name)}</b>${UI.vf(u)}<div class="muted small">@${esc(u.handle)}</div></span><b>${U.short(e.score)} <span class="muted small">${unit[cat]}</span></b></div>`; }).join('')}</div>`; };
    v.addEventListener('click', e => { const p = e.target.closest('[data-p]'), c = e.target.closest('[data-c]'); if (p) { per = p.dataset.p; draw(); } if (c) { cat = c.dataset.c; draw(); } }); draw();
  } });
})();
